### ISSUE TITLE
[Issue] Error creating store

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1158]
I am getting error while creating store after update. I am using the latest updated versions.

![2022-11-06_01-45-44](https://user-images.githubusercontent.com/102427740/200144167-b36988b8-5962-4f9a-9c3d-71e51756202e.png)

**Comment by Blair2004** [comment]
Your issue is not well formatted. At least, you should provide all the version of the module you're using. especially for the multistore module you're using.

**Comment by Blair2004** [comment]
Subsequent issues not having the correct format will be closed. Make sure to read #501 to see how to create an issue.
Thank you.

**Comment by lim10soft** [comment]
Nexo MultiStore Module
Last Version : v4.8.3
You're using
 [NexoPOS 4.8.7]

i am getting error while creating store

**Comment by lim10soft** [comment]
My problem is still ongoing, I can't create a store in the new version

**Comment by Blair2004** [comment]
Hi, 
We need to access your server so this means one of our agent needs to take a look at your server (one is available for Monday). Get in touch at contact@nexopos.com

**Comment by lim10soft** [comment]
What time is the mail sent by country?

**Comment by lim10soft** [comment]
can you give the hour

**Comment by Blair2004** [comment]
Hi,
We're working from 9am to 6pm gmt+1
From Monday to Friday

9am to 1m gmt+1 on Saturday 

Let me know if you have other questions

**Comment by Blair2004** [comment]
Hi, we noticed your issue is based on the version v4.8.3 of multistore. Have you downloaded the version v4.8.4 available on the marketplace ? https://my.nexopos.com/en/marketplace/item/nexo-multistore-module

**Comment by nexopos** [comment]
Closed for inactivity.
