### ISSUE TITLE
[Issue] error when updating to the latest version of gastro

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1159]
**Describe the bug**
error when updating to the latest version of gastro

**To Reproduce**
1. Go to update module

**Screenshots**
![Captura de pantalla 2022-11-06 a las 00 15 48](https://user-images.githubusercontent.com/80654041/200153683-759a6503-1ae2-415f-92da-984df5f421da.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.8.7]
 - Premium Extensions: [Gastro (4.8.10)]

**Comment by Blair2004** [comment]
Thank you. We're reviewing this.

**Comment by Blair2004** [comment]
Hi, we're unable to reproduce this. Please contact the premium support as soon as possible to review your installation.
