### ISSUE TITLE
[Issue] gastro stops working when activating multistore

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1166]
**Describe the bug**
gastro stops working when activating multistore

**To Reproduce**
Deactivate multistore and go to the pos, all the gastro menus are seen, then go to activate the multistore module and go to the pos of a store and the gastro options are no longer seen

**Screenshots**
GASTRO WITHOUT MULTISTORE
![Captura de pantalla 2022-11-08 a las 03 38 05](https://user-images.githubusercontent.com/80654041/200493402-6f64e79a-afd1-40b8-aade-d6759b8ff2c8.png)

GASTRO WITH MULTISTORE
![Captura de pantalla 2022-11-08 a las 03 39 41](https://user-images.githubusercontent.com/80654041/200493544-98d4328f-d823-439c-94a3-710b578ee7fb.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.8.8]
 - Premium Extensions: [Nexo Print Adapter (4.7.5), Gastro (4.8.10), MultiStore (4.8.4]]

**Comment by Blair2004** [comment]
Hi, can you share a screenshot of the console when it's not working correctly ?

**Comment by ahorasoyfelipe** [comment]
it is strange, since if I load the console when it does not work it does not throw an error in the console
![Captura de pantalla 2022-11-08 a las 15 42 15](https://user-images.githubusercontent.com/80654041/200650479-5fec9d8e-c4af-42d7-8600-f04371701597.png)

but if I get this error when I have disabled the multistore module
![Captura de pantalla 2022-11-08 a las 15 46 48](https://user-images.githubusercontent.com/80654041/200650574-9cd62e84-dae1-4257-b5e9-b0e83eb34ac1.png)

![Captura de pantalla 2022-11-08 a las 15 47 11](https://user-images.githubusercontent.com/80654041/200650623-4a43911a-b1c1-4fc8-a6f7-379b665752c9.png)

**Comment by Blair2004** [comment]
After further check, this errors means Gastro wasn't able to inject the "Hold" button, this should completely make the script inactive. If no gastro buttons appears on top, it means Gastro wasn't able to load properly. Usually this error is caused by a symbolic link missing fixed with:

```
php artisan modules:symlink NsGastro
```

By default, this is executed everytime the module is enabled. The error might then be caused by something else, we would like to take a look for a better understanding.

**Comment by Blair2004** [comment]
After a deeper review, we noticed it's not working indeed. We're working on a fix.
