### ISSUE TITLE
[Issue] Getting 404 Not Found error for Dashboard

### ISSUE THREAD

**Issue by peacenharmony** [Blair2004/NexoPOS#1202]
**Describe the bug**
I did download and install the product following instructions here https://my.nexopos.com/en/documentation/getting-started/download-and-install

**To Reproduce**
1. Go to '/nexopos-4x/public'
2. Click on 'Dashboard'
3. See error

**Expected behavior**
View dashboard

**Screenshots**
/nexopos-4x/public shows me this page

<img width="563" alt="image" src="https://user-images.githubusercontent.com/32682589/206108891-fcb01eda-d954-4a4a-b2e5-af06d4b1c6a5.png">

However, Dashboard/ Sign In/ Sign Up gives me 

/nexopos-4x/public/dashboard

<img width="231" alt="image" src="https://user-images.githubusercontent.com/32682589/206110809-a2fa230d-b426-45aa-a46e-6fd4d6bbc1e0.png">

**Environment:**
 - NexoPOS 4.x: 4.8.10

**Comment by Blair2004** [comment]
Hi, you might not have installed correctly. On the URL there shouldn't be the "public" directory.

Make sure to check those tutorial to ensure your Document Root point to the "public" folder:

- [Install on cPanel](https://my.nexopos.com/en/documentation/how-tos/how-to-install-nexopos-from-the-cpanel)
- [Install on Hostinger](https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-hostinger)
- [install on plesk](https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-plesk)

What is your actual environment ? Hosted online ? Using nginx or Apache ?

**Comment by peacenharmony** [comment]
Hi @Blair2004 !

> What is your actual environment ?
it is hosted online with Apache.

> you might not have installed correctly
I suspect that. I followed the docs and completed update upto [Download and Install](https://my.nexopos.com/en/documentation/getting-started/download-and-install) How do I get the [Installation Wizard](https://my.nexopos.com/en/documentation/getting-started/installation-wizard)

**Comment by Blair2004** [comment]
Consider sharing your Apache configuration file NexoPOS.

**Comment by peacenharmony** [comment]
Attached (renamed to .txt so that Github can take it)

[apache2.conf.txt](https://github.com/Blair2004/NexoPOS/files/10174117/apache2.conf.txt)

**Comment by Blair2004** [comment]
Hi, 
This is the default apache configuration, not the apache configuration made for NexoPOS. We need the configuration that indicate  Apache where the app is. Thanks.

Note that every premium purchase gives right to a free installation on a compatible server.

**Comment by peacenharmony** [comment]
Hey @Blair2004, where can I make a premium purchase?

**Comment by Blair2004** [comment]
You just needs to get a license on codecanyon. 

https://codecanyon.net/item/nexopos-4x-pos-crm-inventory-manager/31188619

**Comment by Blair2004** [comment]
Closed for inactivity.
