### ISSUE TITLE
[Issue] Images not showing for products

### ISSUE THREAD

**Issue by yasirmturk** [Blair2004/NexoPOS#1208]
**Describe the bug**
I have uploaded images for the product and also set one as primary but it is not loading on the POS. the image link is not broken but it does not render the respective tag

```
<img v-if="data.galleries && data.galleries.filter( i => i.featured === 1 ).length > 0" :src="data.galleries.filter( i => i.featured === 1 )[0].url" class="object-cover h-full" :alt="data.name"> // this one is not rendering
                         
<i v-if="! data.galleries || data.galleries.filter( i => i.featured === 1 ).length === 0" class="las la-image text-6xl"></i> // this one is rendering
```
<img width="939" alt="Screenshot 2022-12-14 at 7 26 16 PM" src="https://user-images.githubusercontent.com/306691/207679680-76e0b141-f1be-4daf-8ccd-c550c5daa0c9.png">

**To Reproduce**
1. Go to '.../dashboard/products'
2. Click on 'any product'
3. Upload images & make one primary
4. Open POS but images not loading instead placeholder icon is displayed

**Expected behavior**
If you know why this is causing just let me know, I will fix and raise a PR

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.4
 - Premium Extensions: -

**Comment by Blair2004** [comment]
Hi, 
Unfortunately this issue can't be reproduced on 4.8.10.

[This might be](https://my.nexopos.com/en/documentation/troubleshooting/broken-media-images) relevant to your mater. Note that issues must be opened on latest release per branch. The latest release of the branch v4.8 is v4.8.10.

Thank you for your contribution however.

**Comment by yasirmturk** [comment]
Thank you, I will try again with latest release. Can you share with me what release script do you use for deployments and stuff? after I make any change  or run `npm run prod` a lot of files get changed

**Comment by Blair2004** [comment]
I'm not sure to understand the question.
