### ISSUE TITLE
[Issue] Note Problem When Taking Order

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1215]
When I enter 2 products on the ticket, I cannot write a different note for each product.

https://user-images.githubusercontent.com/102427740/208314896-89176a3d-ef63-4c89-864b-ad6b8974b604.mp4

**Comment by Blair2004** [comment]
Hi, thank you for reporting. Make sure to watch this to understand how to create issue

https://www.youtube.com/watch?v=OilNCkiEhDM
