### ISSUE TITLE
CSRF Token Mismatch

### ISSUE THREAD

**Issue by philyando** [Blair2004/NexoPOS#1216]
**Describe the bug**
I locally installed NexoPos 4 but on trying to do register or sign in it always says there is a CSRF Token Mismatch.

![TOKEN](https://user-images.githubusercontent.com/32866949/208329710-d9b7b551-1448-4c0f-a309-64c2adb86a72.jpg)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Hi,
This should help https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-csrf-token-mismatch-on-nexopos-4-x

**Comment by Blair2004** [comment]
If the error is not solved using those instructions feel free to open another thread.

**Comment by philyando** [comment]
Thank you very much for your quick response. The solution you provided worked.
Everything is working fine now. 

One other thing I need assistance with is how to automate the "php artisan serve" command in Windows Powershell.
