### ISSUE TITLE
[Issue] Double subtraction of stock in partially paid orders

### ISSUE THREAD

**Issue by xaviercri** [Blair2004/NexoPOS#1220]
**Describe the bug**
When holding order, the product is subtracted from inventory, but when resuming the order and closing it, inventory is subtracted again.

**To Reproduce**
1. Add products to the order that have "Stock Management Enabled" active
2. Partially apply the payment, at that moment the order is saved and the product is downloaded from stock
3. Open the previously paid order and complete the payment, this will download the stock product again
4. See error screenshots 4

**Expected behavior**
When opening the partially paid order and closing it, you should no longer subtract the products from stock that you previously did

**Screenshots**
screenshot 1
![image](https://user-images.githubusercontent.com/121076939/208594011-6e397b9a-4e3a-44c7-a979-ed874a9caed3.png)

screenshot 2
![image](https://user-images.githubusercontent.com/121076939/208595338-125a9ef5-68af-455c-ba64-abb497d53d0d.png)

screenshot 3
![image](https://user-images.githubusercontent.com/121076939/208595440-35da6fba-189a-4503-811f-68b0584c781d.png)

screenshot 4
![image](https://user-images.githubusercontent.com/121076939/208595586-4236d9a5-5328-485c-8b43-9ec20676e9a9.png)

**Environment:**
 - NexoPOS 4.x vesrion: [4.8.10]
 - Premium Extensions: [Multistore(4.8.5)]

**Comment by Blair2004** [comment]
Hi, thank you for reporting. We'll check this in deep.

**Comment by xaviercri** [comment]
@Blair2004 Thanks for your answer, maybe you can help me with an estimated time for the solution.
