### ISSUE TITLE
[Issue] Available stock validation error

### ISSUE THREAD

**Issue by xaviercri** [Blair2004/NexoPOS#1235]
**Describe the bug**
When opening a partially paid order, you are validating the stock and if it is lower, it gives an error, even though that amount was previously discounted

**To Reproduce**
1. We add a product to the cart, leaving an amount less than the amount entered in stock.
Example.
Cart Itm 7unit
Stock Itm 1unit
2. we apply a partial payment and save it
3. we open the partially paid order and try to close it
4. at that moment an error is displayed indicating that we do not have enough stock.

**Expected behavior**
In this case, I apply the stock validation without taking into account that the quantity had already been discounted.

**Screenshots**
1. partially paid order
![image](https://user-images.githubusercontent.com/121076939/209697935-24160a31-4ed1-450e-9aa1-60cf50bdc47f.png)
2. Unload inventory quantity 7 and leave 1 in stock
![image](https://user-images.githubusercontent.com/121076939/209698062-7c670816-758e-453c-92f5-ed77ea9442ad.png)
3. Error message indicating that you cannot download 7 units out of a stock of 1.
![image](https://user-images.githubusercontent.com/121076939/209698169-58a59fdd-3002-411e-a3d3-4e90f18fe6c6.png)

**Environment:**
 - NexoPOS 4.x vesrion: [4.8.11]
 - Premium Extensions: [Multistore (4.8.5)]

**Comment by Blair2004** [comment]
Hi,
Do you confirm you're using the multistore module ? with NexoPOS at version 4.8.11 ?

**Comment by Blair2004** [comment]
I wasn't able to reproduce this on 4.8.11, please confirm the above information.

**Comment by xaviercri** [comment]
Hello, if I use the multistore module with version 4.8.11, I am going to prepare a video where I show the entire process to reproduce the bug.

**Comment by xaviercri** [comment]
Attached the video of how to replicate the bug.

[NexoPOS ISSUE #1235.webm](https://user-images.githubusercontent.com/121076939/209909117-7f342256-d195-4785-9650-8e522b75a759.webm)

**Comment by Blair2004** [comment]
Thank you. It will be checked.
