### ISSUE TITLE
[Issue] I have a Turkish character problem.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1259]
I've been having this problem for a long time, no help to solve it and my customers are complaining. I am buying a lot of nexo print server licenses from you and will be getting more. I need your help.
![2023-01-09_16-09-42](https://user-images.githubusercontent.com/102427740/211316025-6f4a17e6-771d-4b4d-88fd-621b737b4053.png)

SOLUTIONS I RECOMMEND
Ü=U;ü=u;Ğ=G;ğ=g;Ş=S;ş=s;İ=I;i=ı;Ö=O;ö=o;Ç=C;ç=c=
When I enter these characters, they automatically change to normal characters. In other words, if the entered character is ü, it will turn into the letter u.

2. suggested solution

![210259372-84f2c2ae-9c3c-469b-9ac8-71cd3b924456](https://user-images.githubusercontent.com/102427740/211316763-8a7a1989-944e-4abb-95aa-f6d47e916f90.png)

The character set we set in the printers' own software needs to be set in the software.
but there is no place to set in software

**Comment by Blair2004** [comment]
Hey, we’re aware of the issue you’re facing using the print software in
your language. We’re making everything we can to improve the experience
regardless of the language.

We might need to talk with you privately for further collaboration.

Thank you for your understanding.

**Comment by lim10soft** [comment]
https://github.com/Blair2004/NexoPOS/issues/1259

**Comment by Blair2004** [comment]
We have added image printing on recent NPS Adapter. Reach out privately so we can add it to your system.
