### ISSUE TITLE
[Issue] Double Entry of Procurement transaction on Cash Flow when 'Payment Status' changes from 'Unpaid' to 'Paid'

### ISSUE THREAD

**Issue by lezeski** [Blair2004/NexoPOS#1265]
**Describe the bug**
A Procurement transaction that has an initial Payment Status of 'Unpaid', will record twice under "Accounting->Cash Flow History", if the Payment Status is later set to "Paid". This therefore results in doubling the value. The same doubled value also appears on the dashboard under expenses and the chart.

**To Reproduce**
1.Perform a Procurement transaction with payment status as "Unpaid"
2.Afterwards, set the payment status as "Paid"
3. Navigate to the menu, "Accounting->Cash Flow History"
4. See double debiting of transaction 

**Expected behavior**
A single entry is expected

**Screenshots**
AFTER CHANGING STATUS TO "PAID" 
![image](https://user-images.githubusercontent.com/122467997/211860543-248b44ae-7802-4f06-b498-9c5b48a15036.png)

![image](https://user-images.githubusercontent.com/122467997/211860168-b997ba17-5f48-4d75-8ab5-127943dff086.png)
![image](https://user-images.githubusercontent.com/122467997/211860817-d352fba5-c487-4f29-a7fb-3f51e031d89c.png)

**Environment:**
 - NexoPOS 4.8.13

**Comment by Blair2004** [comment]
Thanks we're reviewing
