### ISSUE TITLE
net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by Boors96** [Blair2004/NexoPOS#1268]
Hi
am getting these tow errors on setup, when I click save database

Errors on console: 
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

GET http://127.0.0.1:8000/api/nexopos/v4/setup/database net::ERR_CONNECTION_RESET

Errors on snackbar: 
1- Network Error
2- You need to define database settings

Note: 
- I did get make the modifications on .env file for APP_URL, SANCTUM_STATEFUL_DOMAINS, and SESSION_DOMAIN
- Using for contributing purpose, localhost server

**Comment by Blair2004** [comment]
Hi

It's not advised to use the built-in server to deploy NexoPOS.
The reason of this is that NexoPOS changes the .env files itself which cause the server to reload and make any session invalid.

If you're using Windows, you're invited to either use a virtual server like Laragon or use WSL (Windows Subsystem for Linux)
If you're on Mac, use a virtual sever like MAMP
for Linux, you can configure a real server.

Let me know if those details helps

**Comment by nzian** [comment]
Hi @Blair2004 thank you. Today I merge with current master branch and all my previous axios error removed. I try setup from terminal and its work perfect.

**Comment by Blair2004** [comment]
Nice to hear that 😊


Le lun. 16 janv. 2023, 17:05, Ziauddin Robin ***@***.***> a
écrit :

**Comment by Boors96** [comment]
Thank you, that was helpful
