### ISSUE TITLE
Printing Gateway Using Default Gateway (Default)

### ISSUE THREAD

**Issue by caturputra** [Blair2004/NexoPOS#1275]
On POS Setting I set Printing Gateway using Default Printing (web), but when I try to place an order and when printing a receipt, why doesn't the paper format adjust to the number of items in the receipt, but adjusts the paper format, is there any solution for this?

My Details:
Nexopos version 4.8.13
Chrome version 
![firefox_k9GRQK6XbP](https://user-images.githubusercontent.com/8774702/214907097-fa792c26-0cff-4c62-847d-a9e4744d67f4.png)
109.0.5414.75

**Comment by Blair2004** [comment]
Hi,
We're unable to control the length of the paper printed on the browser, 

you should probably consider using the printer option to adjust the paper size.
