### ISSUE TITLE
overriding translations

### ISSUE THREAD

**Issue by philippe-unitiz** [Blair2004/NexoPOS#1300]
Hi,

This is not exactly a report.

There is a number of translations i'd like to change in the language json files. Is there a proper way to do this or do i have no other choice than editing the files directly ? I tried using `loadJsonTranslationsFrom` through a service provider in a custom module to no avail.

**Comment by Blair2004** [comment]
Hi, you can use app( 'translator' ) to edit existing translation from your module using a service provider.

```php
...
public function register()
{
    app( 'translator' )->addLines([
       'Hello World' => 'Bonjour Chez vous'
    ], 'fr' );
}
```

**Comment by philippe-unitiz** [comment]
That method doesn't seem to work, i'm getting `Undefined array key 1`  because `app('translator')` doesn't exist yet.

If i "delay" the execution of this code by putting it into `boot()`, there is no error but it doesn't override already loaded translations.

At the end of the day, i managed doing what i wanted by extending the translator service like this : 
```php
public function register()
{
	$this->app->extend('translator', function ($translator, $app) {
		$loader = $app['translation.loader'];

		$locale = $app->getLocale();

		// class extending Illuminate\Translation\Translator with a custom get method
		$trans = new MyCustomTranslator($loader, $locale);

		$trans->setFallback($app->getFallbackLocale());

		return $trans;
	});
}
```
