### ISSUE TITLE
[Issue] provide a title for the issue you're facing here

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1339]
canceled orders content error

nexopos versiyon :
4.8.14
gastro pos versiyon : 
v4.8.13

![Snapshot_23-02-21_04-22-23](https://user-images.githubusercontent.com/102427740/220224052-970cb9cb-7f39-4540-9a6e-31facdacd78a.png)
![Snapshot_23-02-21_04-18-06](https://user-images.githubusercontent.com/102427740/220223844-ddbf69a3-1cb5-4012-88e4-b70119f647e3.png)

**Comment by Blair2004** [comment]
Hi,
make sure you haven't enabled merge similar product on the settings.

![image](https://user-images.githubusercontent.com/5265663/231396953-24b0969a-72a9-4baf-9064-1cdc39e20d23.png)

It must be set to NO if you're using Gastro.
