### ISSUE TITLE
[Issue] web printing not working when enable gastro after recent updates.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1346]
Web printing does not work when gastropos is enabled.

![2023-02-27_19-35-34](https://user-images.githubusercontent.com/102427740/221623618-f9fdce77-f26d-4f0c-8e69-b124bff138d6.png)

nexopos versiyon
4.8.14
Gastro 4x - Restaurant Extension
Blair Jersyer
v4.8.13

https://user-images.githubusercontent.com/102427740/221623041-72f32cb7-87f3-44d2-b59d-d6ec52760721.mp4

**Comment by Blair2004** [comment]
Hi, 
consider sharing a copy of this following file modules/NsGastro/Events/NsGastroEvent.php here

**Comment by Blair2004** [comment]
Also provide a copy of the following file modules/NsGastro/Providers/ModuleServiceProvider.php

**Comment by lim10soft** [comment]
I changed the files you mentioned in your new update and my problem is fixed, thank you. I am still waiting for the solution of the nexo print server Turkish character support problem. My customers are bothering me about this issue. I am waiting for your solution to buy more nexoprint servers. Thank you for your attention.

**Comment by mbugikp** [comment]
Which file did you change? I have the same problem.

**Comment by Blair2004** [comment]
Fixed with v4.8.16
