### ISSUE TITLE
I have setup NexoPos 4x but upon creating installation and database update I am getting this error "Attempt to read property "id" on null"

### ISSUE THREAD

**Issue by ElvisA32** [Blair2004/NexoPOS#1352]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by ElvisA32** [comment]
[
![Screenshot 2023-03-01 093152](https://user-images.githubusercontent.com/126548836/222073121-a0cff827-47d6-42b3-acf7-9f31d68f1c4e.png)
](url)

**Comment by ElvisA32** [comment]
Can you please help me clear out the error

**Comment by Blair2004** [comment]
Hi,
We're not able to proceed any request that is not correctly formatted.

What this to understand how your issue should be formatted.

https://youtu.be/OilNCkiEhDM

**Comment by Blair2004** [comment]
Hi,
We're not able to proceed any request that is not correctly formatted.

What this to understand how your issue should be formatted.

https://youtu.be/OilNCkiEhDM

**Comment by danielsonfire** [comment]
I got same issue as well. Migration script issue admin->id.

**Comment by rutvik106** [comment]
@ElvisA32 @danielsonfire any fix for this? I am also facing the same issue.

**Comment by Blair2004** [comment]
Hi,
Make sure to avoid using "PHP artisan serve" instead use s real virtual server

https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon
