### ISSUE TITLE
[Issue] Unsupported print gateway

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1359]
**Describe the bug**
Unsupported print gateway and the close button

**To Reproduce**
1. Go to pos
2. Click on print
3. See error
![Captura de pantalla 2023-02-11 a las 14 03 17](https://user-images.githubusercontent.com/80654041/222621421-68345e12-63a1-44ed-b530-477091e782d8.png)
4. and the close button doesn't work
![Captura de pantalla 2023-03-03 a las 00 13 47](https://user-images.githubusercontent.com/80654041/222622414-0c151655-4059-4b49-b247-2cc4021620b2.png)

the error is the same if i select nexo print server (2x) or if i select nexo cloud print
works only if I select default printing (web)

**Expected behavior**
should print from nps server

**Environment:**
 - NexoPOS 4.8.15
 - Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.14) - NPS Adapter (4.8.5) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by Blair2004** [comment]
Fixed with update 4.8.17
