### ISSUE TITLE
[Issue] nexo print server ssl problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1362]
No detailed information is given for a secure connection, the link for detailed information says different things and it is the wrong link.
![image](https://user-images.githubusercontent.com/102427740/222803654-8400e80e-9520-4dce-b1b6-e374274b07de.png)
For configuring the certificate, we invite you to [read the following tutorial](https://support.kaspersky.com/CyberTrace/1.0/en-US/174127.htm).  this link does not work and constantly asks for permission, most of the time the printers do not work without permission. Can you help me is there any solution for this.

**Comment by Blair2004** [comment]
Hi,
This is the big threat of Nexo Print Server. 

If you use the SSL, you should note that Nexo Print Server uses self signed certificate which force you to approve before using.

The work around is to have your website (NexoPOS) not using SSL and then you can use Nexo Print a server without SSL as well.

We're adding a fast cloud printing to Nexo Print Server 5.

Hope this will help.

**Comment by lim10soft** [comment]
Unfortunately, the problem is not solved as you describe. If the server is https, the nexo print server does not see the printers when it is http. in the same way, when the server and printer are http, they do not see it, laragonda sees it, but it is not seen on the server. If the server is used, there must be https on both sides, otherwise the printers are not visible.

**Comment by Blair2004** [comment]
Hi, 
The alternative solution solution is to no use SSL on both NexoPOS and Nexo Print Server.
