### ISSUE TITLE
[Issue] no information on the dashboard

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1366]
**Describe the bug**
no information on the dashboard

**To Reproduce**
1. Go to Dashboard
2. See error
![Captura de pantalla 2023-03-06 a las 16 32 05](https://user-images.githubusercontent.com/80654041/223211881-f56f856c-b358-4d17-8e5f-830490b5e177.png)

I have used this command (php artisan ns:report --compute --from=xxxx/xx/xx) for previous dates and nothing, and when making new sales they are not reflected in the dashboard either, only in the reports

**Expected behavior**
You should be able to see all the sales information, daily weekly, etc.

**Environment:**
NexoPOS 4.8.15
Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.14) - NPS Adapter (4.8.5) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by ahorasoyfelipe** [comment]
thanks, mail sent

**Comment by Blair2004** [comment]
Hi, did you received any reply so far ?

**Comment by Blair2004** [comment]
Closed for inactivity
