### ISSUE TITLE
[Issue] Possible wrong calculations for Stock Flow Records

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1370]
**Describe the bug**
I guess the calculations are wrong when you try to Void an order with a refund and return products.
Then when you do a delete on the order.

**To Reproduce**
On void it does a proper stock update. But if you delete the order, it does an additional update to the inventory.

**Expected behavior**
If the stock was updated on order void and return, it shouldn't update again when we delete the order.

**Environment:**
 - NexoPOS 4.8.15

**Comment by Blair2004** [comment]
Thanks for reporting we're reviewing.

**Comment by Blair2004** [comment]
Hi,
We're curious. How do you void a partially refunded order ? We're not able to do that.
Let us know.

**Comment by JosephELKHOURY** [comment]
Hey,

I can't void a partially refunded order.

Scenario:
You have 15 bottles of water in your stock.
You create a new order and sell 3 bottles.
Stock is now 12.

Go to orders and void the order you just made.
Stock is now back to 15.
Go to order and delete the same order you just voided.
Stock is now 18.
