### ISSUE TITLE
[issue] Delivery Status Doesn't Change Regardless of the Cooking status of Meals on Gastro

### ISSUE THREAD

**Issue by MediaPlanSTUDIO** [Blair2004/NexoPOS#1371]
**Describe the bug**
1) Delivery status and process status of orders display pending even in orders where the product Gastro options we choosed Skip Cooking. 
2) When i open Wallet history of the customer i receive this message(photo2)

**To Reproduce**
1. Go to 'POS'
1.2. Make a new order with a product ready made(Product where Skip Coocking Option)
1.3. Go to Orders and see the status Delivery Status and Proccess Status
2.1 Go to Customers
2.2 Options/Wallet history

**Expected behavior**
Delivery status and process status display should display delivered and ready in orders where the product Gastro options we choose Skip Cooking.

**Screenshots**

![WhatsApp Image 2023-03-08 at 09 47 09 (1)](https://user-images.githubusercontent.com/127296868/223676113-459a060b-8cfe-4e17-be42-d2e7df2bbaed.jpeg)
![WhatsApp Image 2023-03-07 at 21 40 41](https://user-images.githubusercontent.com/127296868/223676241-32631895-7a1b-4331-945f-9ab9405adc25.jpeg)

**Environment:**
 - NexoPOS 4.8.15
 - Premium Extensions: [NexoPOS MultiStore 4.8.5, Nexo Print Adapter 4.8.5, Gastro 4.8.14]

**Comment by Blair2004** [comment]
Ongoing

**Comment by Blair2004** [comment]
The **Process Status** And the **Delivery status** are statuses that are updated by the user on the order options. It wasn't made to be changed by Gastro based on the cooking status. Gastro has his own status it creates for products.

Final words, we don't plan to make Gastro updates those columns (Process Status & Delivery Status) respectively. Consider using the order options for changing those values.

![screenshot-nimbusweb me-2023 03 10-13_19_53](https://user-images.githubusercontent.com/5265663/224314697-6ca9313b-5e98-4266-85f6-9a2cb1e05535.jpg)
