### ISSUE TITLE
Cannot Print - Undefined property: stdClass::$id

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS#1373]
**Describe the bug**
After placing an order I cannot print

**To Reproduce**
![Cannot print 001](https://user-images.githubusercontent.com/13999977/224285160-67364aaf-6fc5-4f20-9782-2845c2eb2ff0.png)

To throw an error  go to

![Orderlist Receipt error 001](https://user-images.githubusercontent.com/13999977/224285348-967f6f6e-46c7-4de3-891b-c365f1899568.png)

then
![Orderlist Receipt error -undefined property stdclass](https://user-images.githubusercontent.com/13999977/224285420-31fa0f1c-9dd7-4630-8f86-970187f1706a.png)

**Expected behavior**

print receipt
**Screenshots**

**Environment:**
 - NexoPOS 4.8.15 ]
 - Premium Extensions: Nexo Print Adapter (4.8.5), Gastro (4.8.14)]

**Comment by Blair2004** [comment]
Hi,

This error occurs when grouping similar products is enabled. Once a product is merged with other similar product, Gastro needs to know from which id it should pull the modifiers that are attached.

We believe that option shouldn't work for product having modifiers. We'll end having a product that sums all modifiers. What if 2 similar products has different sale price and one has a discount and the other doesn't ?

Consider disabling that feature. It will be removed on upcoming release

![image](https://user-images.githubusercontent.com/5265663/224312524-bf5428b4-d93c-4208-a7ca-0cbf39741858.png)

Close the issue if that solve your problem.

**Comment by mbugikp** [comment]
Thank you. I can now print. Kindly consider ticket https://github.com/Blair2004/NexoPOS/issues/1367 and https://github.com/Blair2004/NexoPOS/issues/1368.
