### ISSUE TITLE
[Issue] Sales by Payments Types

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1375]
**Describe the bug**
Sales by Payments Types is calculating all payments including those that belong to voided orders.
Shouldn't count only orders who are fully paid and not voided?

**To Reproduce**
1. Go to Reports->Sales By Payments

**Expected behavior**
Instead of 
`$payments = OrderPayment::where( 'created_at', '>=', $startRange )
            ->where( 'created_at', '<=', $endRange )
            ->whereIn( 'identifier', $paymentsIdentifier )
            ->get();
`
It should be
`$payments = OrderPayment::where( 'created_at', '>=', $startRange )
            ->where( 'created_at', '<=', $endRange )
            ->whereIn( 'identifier', $paymentsIdentifier )
           ->whereRelation('order', 'payment_status', Order::PAYMENT_PAID)
            ->get();
`

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.15

What do you think?

**Comment by Blair2004** [comment]
Yes, you're right.
Feel free to submit a PR on this.

**Comment by josephelkhoury** [comment]
#1363

**Comment by Blair2004** [comment]
Hey, That pull request doesn't includes those change.  🤔 did i miss something ?

**Comment by josephelkhoury** [comment]
Sorry my bad, I included in a pull request that has other changes as well.

**Comment by josephelkhoury** [comment]
#1378
