### ISSUE TITLE
[Issue] When products are put on hold, they are not deducted from inventory even when they are sold, but products that are sold without being put on hold are deducted from inventory.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1376]
**Describe the bug**
When products are put on hold, they are not deducted from inventory even when they are sold, but products that are sold without being put on hold are deducted from inventory.

https://user-images.githubusercontent.com/102427740/224772076-6d0d3017-09b0-495c-93e7-cef7821d7ae1.mp4

**Comment by Blair2004** [comment]
Hi,
Your issue doesn't follow the conversion of submitting issue. This barely gives us more informations about your envrionment, your modules and other useful details for handling your issue.

Make sure to check this #501 to understand how to create an issue.

**Comment by lim10soft** [comment]
I took a video of the problem for you, the problem is a very big problem. The product is put on hold and does not fall out of stock after payment is made. I guess you didn't watch the video.

**Comment by Blair2004** [comment]
The video doesn’t mention the module you use, the version of NexoPOS etc.
You can write a thread where you describe the issue and put the video along
with the version that will help us understanding

**Comment by lim10soft** [comment]
https://user-images.githubusercontent.com/102427740/225075732-440eae72-7bc7-42a3-b721-0910bdc067ad.mp4

In the video, I specified the versions of all my modules and the nexo pos versions. My Problem When orders are put on hold, they are not out of stock. Orders put on hold do not fall out of stock after payment.

**Comment by Blair2004** [comment]
We're going to take another look at this thread.
