### ISSUE TITLE
When products are put on hold, they are not deducted from inventory even after they are sold.

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS#1389]
**Describe the bug**
When products are put on hold, they are not deducted from inventory even when they are sold, but products that are sold without being put on hold are deducted from inventory

**To Reproduce**
Check one product quantity.
Sell the product, put it on hold or if using gastro send to the kitchen, check the quantities, quantity does not change.
Now sell the same product don't send it to kitchen, don't put it on hold, receive payment immediately.
Check quantities, quantity has changed.

**Expected behavior**
Stocks (quantity) should reduce after sale

**Screenshots**

**Environment:**
 - NexoPOS 4.8.15
 - Premium Extensions: [e.g Nexo Print Adapter 4.8.5, Gastro 4.8.14

**Comment by mbugikp** [comment]
https://github.com/Blair2004/NexoPOS/issues/1376

**Comment by Blair2004** [comment]
Please clarify.

So you mean, when an order is on hold, the stock is not deducted.
However, when you process to a payment directly, the stock is deducted ?

We haven't made Hold order to deduct the stock as at the moment of processing, hold order aren't likely to be purchased by the customer. It's more like a paused order. Hold order is different for an unpaid order (which is expecting a payment). Not sure if that make any sence for you.

Let me know.

**Comment by mbugikp** [comment]
@Blair2004 
"**Please clarify.
So you mean, when an order is on hold, the stock is not deducted.
However, when you process to a payment directly, the stock is deducted ?"**

This is true.
Any order that is held, then processed for payment stock is not deducted, but when you process payment directly the stock is deducted.

**Comment by mbugikp** [comment]
@Blair2004 
"**We haven't made Hold order to deduct the stock as at the moment of processing, hold order aren't likely to be purchased by the customer. It's more like a paused order. Hold order is different for an unpaid order (which is expecting a payment). Not sure if that make any sence for you.**"

When using POS an order is a direct request made by a customer who wants to eat, drink or both, it is highly unlikely a customer will come make an order to eat, proceed to seat down then cancel the chances of that occurring is 1 out of 10, which when it occurs we simply void that order and stocks are returned. Stocks should be deducted on order, this is especially true for hotels and restaurants. 
What you are trying to implement will work for wholesalers, retailers and online shops, by adding an Add Sale Menu (not POS) where orders can be paused until payment or delivery, that would involve and sales order processing, 
Sales order which will have different status like draft, pending, final, delivered, etc.
But for hotels, bars and restaurants order=stock deduction.

Regards

**Comment by Blair2004** [comment]
I agree with this. But remember, we're here talking about NexoPOS first, which is mainly made for retails. So we'll consider this scenario for Gastro. In fact order sent to the kitchen should now have a status of "unpaid" instead of "hold". An unpaid order has the inventory deducted.

**Comment by mbugikp** [comment]
Unpaid status for orders sent to the kitchen should work for gastro, when will this change be effected?

**Comment by mbugikp** [comment]
How was these issue resolved. Is there an update?

Regards.

**Comment by mbugikp** [comment]
> I agree with this. But remember, we're here talking about NexoPOS first, which is mainly made for retails. So we'll consider this scenario for Gastro. In fact order sent to the kitchen should now have a status of "unpaid" instead of "hold". An unpaid order has the inventory deducted.

@Blair2004 When will these be implemented? If it is taking time you could direct me to the code I change as we wait for 4.8.16 or we down grade to 4.8.14, 4.8.13 which will have inventory deducted.

**Comment by Blair2004** [comment]
This is fixed with 4.8.16
