### ISSUE TITLE
Annual Report & Sales by payment report not in sync with Sales report

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS#1391]
**Describe the bug**
Then Annual Report & Sales by payment report are not in sync with Sales report, The sales report gives an accurate figure of sales amount sold but the annual report & sales by payment are not updated.

**To Reproduce**
Make a sale and receive payment, check all the three reports above.
Make another sale but put it on hold, then receive payment, check all the three reports above.
Make a third sale and receive payment, check all the three reports above. 

**Expected behavior**
You should find all the three reports tallying however, only the sales report will give an accurate report of all the three transactions, the 
Annual Report & Sales by payment report will not be fully updated.

**Screenshots**
The accurate & updated sales report
![taxes report](https://user-images.githubusercontent.com/13999977/225723778-8bc09732-2260-4878-91d9-d579487da161.png)

The erroneous annual report
![annual report error](https://user-images.githubusercontent.com/13999977/225724126-71f5d464-2680-479d-ad99-3a691a5bf009.png)

The inaccurate sales by payment report
![sales by payment report error](https://user-images.githubusercontent.com/13999977/225724354-cdaed08d-c359-4e0f-8a20-3bba4dac4065.png)

**Environment:**
 - NexoPOS 4.8.15
 - Premium Extensions: [e.g Nexo Print Adapter (4.8.5), Gastro (4.8.14)]

**Comment by Blair2004** [comment]
Hi,
The payment report is the amount received as a specific payment type... this doesn't include changes. So, that amount will always tend to be greater than the sale report.

Anyway, following your steps, we'll try to reproduce this.

Thank you.

**Comment by mbugikp** [comment]
@Blair2004 Kindly check payment report, sales report and annual report as detailed above.

Regards

**Comment by Blair2004** [comment]
Hi, 
After further tests, we're not able to reproduce this. Some reports might not tally with the current figures if you haven't configured workers (background tasks). From our side all report was updated correctly following the steps you mentionned.
