### ISSUE TITLE
ENV file deletes itself even after updating, Stock not depleting for products sold, unable to view & reprint receipt

### ISSUE THREAD

**Issue by newidea4rmmike** [Blair2004/NexoPOS#1400]

**Comment by Blair2004** [comment]
Hi, Thank you for submitting your first issue.
title aren't use to give a description of an issue. If you have many issue, open ticket for each issues separately.
You might also need to ready this #501 to understand how to create an issue...this is very important.

Issue that aren't correctly formatted are rejected.
