### ISSUE TITLE
[Issue] Unable to process payments. Invoices remain on hold.

### ISSUE THREAD

**Issue by mbk87234** [Blair2004/NexoPOS#1417]
I installed NexoPOS on a fresh server and restored backed-up data with the help of customer support.
However, I am facing two issues now.

1. Some invoices do not include the tax amount.
To solve this issue, I tried customizing the receipt blade. However, now some invoices have correct tax and totals while others have either incorrect amounts of tax or incorrect totals.

2. The second issue I am facing is that I cannot process any payments. When I check the console, it gives 403 error on api requests like this 
![image](https://user-images.githubusercontent.com/48960885/230706900-53bca70d-60c6-4bb5-b7d1-616217a7ee78.png)

**To Reproduce**
1. Create a new order.
3. Click on 'Pay'
4. Pay through cash or card
5. An empty red error message pops up and the console shows the 403 error

**Expected behavior**
All invoices should have 15% VAT, added to totals.
Payment should proceed and be included in the weekly and monthly reports as well as the customers report.

**Environment:**
 - NexoPOS [vesrion 4.8.11]
 - Gastro [version 4.8.8]

**Comment by Blair2004** [comment]
Hi,
In your screenshot, it seems like you're trying to update an already existing order.
The steps you shared might not be accurate. Can you proceed step by step explaining from creating a new order?
Kind regards.

**Comment by mbk87234** [comment]
The issue was related to apache server, not NexoPOS itself.
