### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by otakuventure** [Blair2004/NexoPOS#1430]
**Service Charge**
In Asian Country, especially in Malaysia. 
we have a service Charge which is a common feature for dine-in
exclude tax

**To Reproduce**
1) Dine-In order
2) service charge will be a fix-variable amount set in admin.
3) Percentage of total food prices 

**Expected behavior**
For example
Coke is 2$
noodle is 3$

Coke x 3 = 6$
noodle x 2 = 6$

Total Food Price is = 12$
Total Service tax 10% = 1.2$
Total Tax 6% = 0.72
Total food price = 13.92
Rounding = -0.02
Grand Total = 13.90

**Screenshots**

**Environment:**
Core Version | 4.8.11
Laravel Version | 9.52.4
PHP Version | 8.2.4

**Comment by Blair2004** [comment]
Hi, thank for you suggestion. Actually, NexoPOS offer a multiple tax system. This means that you can apply more than one tax to a single order. 

Additionally, you can create what we call quick product directly on the pos. This product has no inventory and his price is set during the checkout process. That product can have a fixed price or percentage based (on the order subtotal).

We believe with those, it's not necessary to add an additional tax as NexoPOS already offer the flexibility for that.

Hope this helps.

**Comment by otakuventure** [comment]
![image](https://user-images.githubusercontent.com/69811457/232556804-bb0e66eb-78ff-468d-960f-253485ed1a63.png)
I have already setup the tax above
![image](https://user-images.githubusercontent.com/69811457/232556893-6dce8e9c-12d8-4ddd-86a1-867f878e6d8e.png)
The tax is not appearing in my POS
![image](https://user-images.githubusercontent.com/69811457/232557228-6ba828be-e0e7-4847-8dcd-f8ad10b48637.png)
When i click the tax setting , the mouse cursor is disable unable to select the tax. 

Do provide the steps to enable this tax setting.

**Comment by Blair2004** [comment]
Hey, check the tax settings on General Settings > POS

**Comment by otakuventure** [comment]
@Blair2004 
I have tried the tax setting.
1) The requested task for this is a service charge, earlier was a typo
2) I have tried add products , using dynamic as product type. 
However, this has caused the calculation to goes wrong. 
3) The service charge in our country regulation is exclude any tax. (none taxable by the government )

Current system
For example
Coke is 2$
noodle is 3$

Coke x 3 = 6$
noodle x 2 = 6$

Total Food Price is = 12$
Total Service Charge 10% = 1.2$ <<-- using dynamics products
Total Tax 6% = 0.792
**Total food price = 13.792**

Expected - in our country service charge is none taxable
For example
Coke is 2$
noodle is 3$

Coke x 3 = 6$
noodle x 2 = 6$

Total Food Price is = 12$
Total Service **Charge** 10% = 1.2$
Total Tax 6% = 0.72
Total food price = **13.92**
Rounding = -0.02
Grand Total = **13.90**
