### ISSUE TITLE
error while back dating an expense

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS#1433]
**Describe the bug**
When you try to backdate an expense there is an error pointing to date format

**To Reproduce**
Go to Expenses add and an expense, change expense date to an earlier date, save

**Expected behavior**
Expenses should accept earlier dates.

**Screenshots**

![back date expense error](https://user-images.githubusercontent.com/13999977/232756090-80e3997f-7a68-49e3-96dd-676e9525300a.png)

**Environment:**
 - NexoPOS 4.x version: [e.g. 4.8.17]

**Comment by Blair2004** [comment]
Please share a screenshot of your date settings

**Comment by Blair2004** [comment]
We cannot reproduce this.

**Comment by mbugikp** [comment]
@Blair2004 you mentioned this " that's because the expense date is not on the format Y-m-d... so for fixing this, we have to format the value in a way mysql can undestand " on  18th April 2023.

**Comment by mbugikp** [comment]
> Please share a screenshot of your date settings

![date format settings](https://user-images.githubusercontent.com/13999977/235058823-08d55067-31a1-4f8f-9773-c70dcd471c68.png)
