### ISSUE TITLE
Table not clear after payment done

### ISSUE THREAD

**Issue by otakuventure** [Blair2004/NexoPOS#1435]
**Describe the bug**
I have turn on Setting : Freed Table After Payment , table status remain "Busy"

**To Reproduce**
1 ) Turn On 
![image](https://user-images.githubusercontent.com/69811457/232954711-82524a27-52ac-4763-a917-220a22f94b5d.png)
2 ) Make an Order
3 ) Make payment 
![image](https://user-images.githubusercontent.com/69811457/232954927-853c25a2-71b4-411e-b439-ec313fc17c08.png)
Table remain busy status
![image](https://user-images.githubusercontent.com/69811457/232954995-aa206306-08e9-4553-ace4-f91c40c80fce.png)
 

**Expected behavior**
Once make payment , table is freed , no longer in busy status, do not need to manual trigger set table free

**Screenshots**
Refer above

**Environment:**
Core Version	4.8.17
Laravel Version	9.52.5
PHP Version	8.2.4

**Comment by Blair2004** [comment]
Hi, after checking the issue, it seems like you should enable "Table Sessions" (on Gastro 4.8.15)
From Gastro 4.8.16, we have removed a setting that confuses users. 

In fact, if you want the system to free tables automatically, table sessions must be enabled. Gastro uses Table Sessions to find out all orders placed by a customer on a table. It then checks whether all those orders are paid and freed the table.

![screenshot-nimbusweb me-2023 04 26-10_44_44](https://user-images.githubusercontent.com/5265663/234537729-39e89847-e615-422c-a3a0-c09fdd053322.jpg)
