### ISSUE TITLE
Change Customer mode Mandatory to Optional

### ISSUE THREAD

**Issue by otakuventure** [Blair2004/NexoPOS#1452]
**Describe the bug**
We and our branch do not use any customer mode,
Currently, we are creating a guess mode to store all this value and the figure keeps adding. 

**To Reproduce**
1. upon payment or send to kitchen 
2. will promt for customers

**Expected behavior**
Option 1. 
Option to disable customer mode totally
Option 2.
Put as guess, no need to record any sales value
Option 3.
Customer mode is not mandatory

**Screenshots**
-

**Environment:**
Core Version 4.8.17
Laravel Version 9.52.5
PHP Version 8.2.4

**Comment by Blair2004** [comment]
Hi,
Thank you. This will be checked.

**Comment by Blair2004** [comment]
![customers](https://user-images.githubusercontent.com/5265663/235001967-2b2c589d-4b36-4297-8ad3-3ea16932ec2e.gif)

Unable to reproduce with NexoPOS 4.8.17.
Make sure you've set the default customers and customers group from the "Customers" setting.

**Comment by otakuventure** [comment]
hi , 

we are looking at order without the need for mandatory assignment to customer. 

This gif file show you have assign a customer to the order, therefore it wont appear.  @Blair2004

**Comment by Blair2004** [comment]
Hi,
An order must be assigned to a customer. You can create a fake customer
that is selected by default each time.

Hope this helps.

**Comment by otakuventure** [comment]
How do we do that , default selected customer ?
