### ISSUE TITLE
[Issue] migration hasn't executed on the substore

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1456]
**Describe the bug**
I updated from version 4.8.15 to 4.8.16 and now I have this error when paying for an order

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_product_id' in 'where clause' (SQL: select count(*) as aggregate from `ns_store_1_nexopos_products_histories` where `order_product_id` = 34 and `operation_type` = sold)

In the same chat where I reported the problem, Blair told me that the migration hasn't executed on the substore.

For now fix that problem, by adding the column manually.

But several problems are already happening and of course it has to do with the fact that the sub stores are not updated

The modifiers work fine since the update, even if I enter that it doesn't ask me for quantity, it does it the same way

I still have this problem too: https://github.com/Blair2004/NexoPOS/issues/1359

I hope you can help me with this

**Environment:**
NexoPOS 4.8.16
Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.15) - NPS Adapter (4.8.6) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by Blair2004** [comment]
Hi, 
For #1359 please update to NexoPOS 4.8.17.
We're checking this reported issue.

**Comment by ahorasoyfelipe** [comment]
I already did it update to 4.8.17, but the substores are not updated, I had to go back to my backup (4.8.16)

**Comment by Blair2004** [comment]
Thank you for reporting. We're investigating.

**Comment by Blair2004** [comment]
Hi, we weren't able to reproduce this issue following those exact same steps. Maybe it's related to the cache not being cleared.

```
php artisan cache:clear 
```
