### ISSUE TITLE
NPS Does not print order when set as the print gateway

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS#1459]
**Describe the bug**
When I set NPS as the print gateway I the below error " the selected print gateway doesn't support this type of printing "

**To Reproduce**
Go to POS settings and set nps as the default print gateway, save.
Go to POS, orders, then print any order. 

**Expected behavior**
NPS should print the order

**Screenshots**
![nps does not print order](https://user-images.githubusercontent.com/13999977/235141581-9b68a940-5b2e-4946-a1d7-fab4f87fbf87.png)
the print error

![printing gateway settings](https://user-images.githubusercontent.com/13999977/235141683-a99e62ec-ce83-4cbd-9462-0619a39ff4ea.png)

![print adapter settings](https://user-images.githubusercontent.com/13999977/235141840-a5a158aa-c37e-4256-990c-1c2fc3aed4f6.png)

![print adapter settings - General](https://user-images.githubusercontent.com/13999977/235141887-dc7e2352-5fa3-471e-b52e-de7b37eac770.png)

Gastro
![Gastro NPS adapter settings](https://user-images.githubusercontent.com/13999977/235141928-6662c9b1-1bd6-4557-b712-d257a2473334.png)

**Environment:**
 - NexoPOS 4.8.17 
 - Premium Extensions: Nexo Print Adapter 4.8.6, Gastro 4.8.15

**Comment by Blair2004** [comment]
Hi, Does cash register are enabled no this setup ?

**Comment by mbugikp** [comment]
Yes, cash register is enabled

**Comment by Blair2004** [comment]
This should have been fixed with Nexo Print Adapter 4.8.8 and NexoPOS 4.8.18

**Comment by mbugikp** [comment]
@Blair2004 I have tested this on Nexo Print Adapter 4.8.8 and NexoPOS 4.8.18 it still has the same error.

**Comment by Blair2004** [comment]
Thank you for reporting. I'll check
