### ISSUE TITLE
Reporting Bugs

### ISSUE THREAD

**Issue by otakuventure** [Blair2004/NexoPOS#1460]
**Describe the bug**

**Report without data**
Sales Report not display
Sales by payment only all 0 

**Report with Data**
Sales Progress have value
Customer Statement have value

**To Reproduce**
1) Open Register
2) Key in sales
3) Close Register
4) Go to report, get report for Sales Report & Sales by payment , by pressing load 
5) Sales Report nth come out
6) Sales by Payment have all the tender type but value all 0

**Expected behavior**

Sales Report to have value for 
Categories details
Categories Summary
Products

Sales by payment type
TO display amount paid for that order

**Screenshots**
Sales Report
![image](https://user-images.githubusercontent.com/69811457/235362419-4aa016e3-f53d-43fe-b309-bf1cda195382.png)
![image](https://user-images.githubusercontent.com/69811457/235362444-df1d961c-f846-4aae-bb4b-2ce74b01ac80.png)

Sales By Payment
![image](https://user-images.githubusercontent.com/69811457/235362462-9a159849-5ab9-4f3b-8b21-3f0ecaac384a.png)

Sales Progress
![image](https://user-images.githubusercontent.com/69811457/235362501-63d24907-5891-4722-b2a7-190bf01412bf.png)

Customer Statement
![image](https://user-images.githubusercontent.com/69811457/235362532-ea0c0eb0-a9cb-4b8a-821d-3c137b04d20a.png)

My Order Table
![image](https://user-images.githubusercontent.com/69811457/235362553-f01b8e5c-121e-44e3-b60f-02be7349815a.png)

**Environment:**
Core Version	4.8.17
Laravel Version	9.52.5
PHP Version	8.1.10

**Comment by Blair2004** [comment]
This error might be related to something else that is not related to NexoPOS. At the moment of writing those reports don't have an error (proof expected to show me wrong). We might need to closely take a look at your server (premium support). Let us know privately. This might also be caused workers not configured.

See #151 for further details.
