### ISSUE TITLE
[Issue] NPS the print gateway does not work when multistore module is active

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1470]
**Describe the bug**
NPS the print gateway does not work when multistore module is active

**To Reproduce**
Go to pos
Click on print
See error

**Expected behavior**
NPS should print the order

**Screenshots**
![Captura de pantalla 2023-05-04 a las 01 38 48](https://user-images.githubusercontent.com/80654041/236120664-708a1be1-56c5-4a68-8c1d-582d34cbe664.png)

**Environment:**
NexoPOS 4.8.17
Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.15) - NPS Adapter (4.8.7) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by Blair2004** [comment]
Hi, 
This has been fixed with NPS v4.8.8 and NexoPOS 4.8.18
