### ISSUE TITLE
[Issue] Modifiers in gastro does not take the options

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1471]
**Describe the bug**
Modifiers in gastro does not take the options

**To Reproduce**

https://user-images.githubusercontent.com/80654041/236122321-24b9de06-a621-4517-8fcf-200360b4ec88.mp4

**Expected behavior**
that works according to the options delivered

**Screenshots**

Modifier Group Configuration
![Captura de pantalla 2023-05-04 a las 01 55 52](https://user-images.githubusercontent.com/80654041/236122484-a9e7ed61-3a17-443e-b111-c698f5a69c94.png)

**Environment:**
- NexoPOS 4.8.17
- Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.15) - NPS Adapter (4.8.7) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by Blair2004** [comment]
Hi, We're not really sure to understand.

**Comment by ahorasoyfelipe** [comment]
If I select the option that the modifier does not ask me for quantity, it does the same, these options are not saved
![236122484-a9e7ed61-3a17-443e-b111-c698f5a69c94](https://github.com/Blair2004/NexoPOS/assets/80654041/f71e454a-13c8-40d7-a287-3b0470a25b8b)

Just as the categories are not saved in the kitchen, it saves them, but when entering again it does not show any
![Captura de pantalla 2023-05-28 a las 19 55 19](https://github.com/Blair2004/NexoPOS/assets/80654041/5b3537a1-0a49-496c-8399-ade19f7b2558)

**Comment by ahorasoyfelipe** [comment]
worked fine in the latest version
