### ISSUE TITLE
[Issue] modifiers charge amount wrong

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS#1475]
**Describe the bug**
modifiers charge amount wrong

**To Reproduce**

The modifiers also present a problem, they load fine the first time, but when reopening the order, the amount goes from (x1) to (x1.00)

**Screenshots**

https://user-images.githubusercontent.com/80654041/236518058-d4254c2d-e1c4-4705-b59c-9f16cc361f4c.mp4

**Environment:**
 NexoPOS 4.8.17
Premium Extensions: MultiStore (4.8.5) - Gastro (4.8.15) - NPS Adapter (4.8.7) - Bulk Importer (4.8.0) - Sales Commissions (4.8.1)

**Comment by Blair2004** [comment]
Confirm the issue persists with Gastro v5. Reopen if that's the case
