### ISSUE TITLE
Permission management Issue

### ISSUE THREAD

**Issue by gurulancer** [Blair2004/NexoPOS#1481]
Even if I set store cashier to create customers, update customers and etc, When Store cashier try to create customer to process pay in open POS, This message is shown "the authorize is not permitted "

How to fix this ?

**Comment by Blair2004** [comment]
Hi,
Please consider providing a screenshot.

Kind regards.

**Comment by gurulancer** [comment]
Here is

https://u.pcloud.link/publink/show?code=XZVJGtVZMYeBal5Y7yXpf3bPiB8ArFATnvYy

https://u.pcloud.link/publink/show?code=XZJJGtVZnFzNcGEy5h7pqt0zQvUJBJY8ggcy

![cashier-create-customer-error](https://github.com/Blair2004/NexoPOS/assets/132946315/e8e90a54-f241-4929-bf53-38aabcb54450)


![cashier-create-customer-error](https://github.com/Blair2004/NexoPOS/assets/132946315/59ca2206-a638-4d7d-8a24-d0b2e938329c)
Thank You

**Comment by Blair2004** [comment]
Hi, 
Go to the POS settings then "Features" tab, there you'll see a control for allowing customer creation from POS. Make sure to enable it.

Hope this helps.

**Comment by nexopos** [comment]
Hi, any update on this @gurulancer ?

**Comment by gurulancer** [comment]
Great !
It solved
Thanks a lot
