### ISSUE TITLE
[Issue] Direct printing does not work in nsgastro table ticket section after your last update

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1512]
https://github.com/Blair2004/NexoPOS/assets/102427740/66fa07a1-da4e-48e4-8741-136dfe54eebb

I need an urgent solution.

**Comment by Blair2004** [comment]
![printning](https://github.com/Blair2004/NexoPOS/assets/5265663/549e06bd-d6d8-442a-8ea5-935f740839f3)
It works from our end.
