### ISSUE TITLE
[Issue] cart not reset when i add product from gastro to ticket in your latest updates

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1514]
https://github.com/Blair2004/NexoPOS/assets/102427740/1feb4ddc-532b-4256-82cc-2de63e615b35

When I add a product to a ticket, the cart needs to be reset, but it doesn't.

gastro version: v4.8.20
nexo versiyon : 4.8.18

**Comment by Blair2004** [comment]
Hi, is the issue persistent ?

**Comment by lim10soft** [comment]
The latest update continues in nexopos and gastro pos

**Comment by Blair2004** [comment]
Confirm the issue persist with Gastro 5. reopen the issue if that's the case
