### ISSUE TITLE
[Issue] In Income and profit tabs Words Are not Visible 

### ISSUE THREAD

**Issue by mayswe** [Blair2004/NexoPOS#1515]
**Describe the bug**
In Income and profit tabs Words Are not Visible 

**To Reproduce**
1. Go to Report
2. Click on Income and profit

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Hi, thank you for trying to contribute. However, your issue is unclear and doesn't give any further indication on how to reproduce and fix this issue. Make sure to read this #501
