### ISSUE TITLE
[Issue] There is a problem with calculating the Total purchase price

### ISSUE THREAD

**Issue by moaaz97** [Blair2004/NexoPOS#1522]
**Describe the bug**
When placing an order, the total purchasing price is being calculated as purchase price for one quantity, not a total purchase price.

https://github.com/Blair2004/NexoPOS/assets/53799123/11496944-a482-403c-943f-d06e4f8476e7
 
**To Reproduce**
1. Go to POS and place an order with a quantity of 5, for example, of some product.
2. Go to database orders_product table, and check the total_purchase_price for that order, you will get that is had calculated the purchase price for only 1 quantity.

**Expected behavior**
The purchase price of that order, should be for 5 quantities.

**Another Problem**
This issue is reflected in the profit report, and calculate the profit with a wrong way.

The code in OrderService class, __saveOrderProducts method:
`
$orderProduct->total_purchase_price = $this->currencyService->define(
                $product[ 'total_purchase_price' ] ?? $this->productService->getLastPurchasePrice( $product[ 'product' ] )
            )
                ->getRaw();
`
Is that right, I think it should be like that:
`
$orderProduct->total_purchase_price = $this->currencyService->define(
                $product[ 'total_purchase_price' ] ?? $this->productService->getLastPurchasePrice( $product[ 'product' ] ) * $orderProduct->quantity
            )
                ->getRaw();
`

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.8.17]

**Comment by moaaz97** [comment]
Hello Blair,
I have made a pull request with the new edit of calculating total purchase price.

**Comment by Blair2004** [comment]
Hi, 
Thank you for your contirbution. We'll review that.
