### ISSUE TITLE
Unable to locate Mix file: /js/bootstrap.min/bootstrap.js.

### ISSUE THREAD

**Issue by mhsharkar2011** [Blair2004/NexoPOS#1542]
WHen I am Going to show the project the error is showing screenshot added
![Screenshot from 2023-06-17 02-09-21](https://github.com/Blair2004/NexoPOS/assets/51879416/f73ed801-1118-4349-a8b9-41221672f408)

**Comment by Blair2004** [comment]
Hi,
Unfortunately, this error is not correctly formatted to ease our understanding of your issue.
Make sure to read #501 to understand how to create an issue.
