### ISSUE TITLE
[Issue] Nexo Print Server 2.x not printing

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1547]
**Describe the bug**
My NexoPOS is running on a server not on local machine.
I've followed all the steps to configure the print server but the order is never printed. 

**To Reproduce**
I get a success message but the printer is not receiving the print job.

**Screenshots**
![image](https://github.com/Blair2004/NexoPOS/assets/1782788/0a0ac8a4-ac69-4062-bb70-0461eb07c23f)

**Environment:**
 - NexoPOS 4.8.18 vesrion
 - Premium Extensions: Nexo Print Adapter (4.8.6), Gastro (4.8.15)

**Comment by Blair2004** [comment]
Hi,
Does NexoPOS is running under https ?
This might prevent Nexo Print Server from being recognized. 

Let us know.

**Comment by josephelkhoury** [comment]
Yes they're both running under HTTPS.

**Comment by josephelkhoury** [comment]
> Hi,
> 
> Does NexoPOS is running under https ?
> 
> This might prevent Nexo Print Server from being recognized. 
> 
> 
> 
> Let us know.

Yes they're both running under HTTPS.

**Comment by josephelkhoury** [comment]
Any solution to that?
We can't use the system with SSL!!

**Comment by josephelkhoury** [comment]
I am trying to set up the cloud printing but it's not working.

I followed all steps in the documentation but it's not very clear and I don't know if I missed anything.

I have my main installation on a remote server.
I set up a new installation on the local computer (where the printer is installed) to be able to print.
Which modules should be installed on each of the 2 installations?

If someone can help because I'm a bit confused.

Thanks.

**Comment by Blair2004** [comment]
Hey,
Cloud Print has been disabled as it's about to be replaced by a new service. 

When using HTTPS, you need need to self approve the certificate available by default. 

We might install an experimental NexoPOS. However before we have question:

- how many computers you plan to use on NexoPOS?
- are you using Gastro ?
- does your website allows http (not secure connection) ?

**Comment by josephelkhoury** [comment]
I have one main computer connected to the printer. It's currently the only computer that is taking orders.
It accesses a remote installation of NexoPOS.
I installed as well a local version of NexoPOS on it that should be used for printing but couldn't make it work.

The printer that is connected to this computer should print receipts as well as kitchen orders.

We might take orders later from a mobile phone or tablet.

**Comment by lim10soft** [comment]
> I have one main computer connected to the printer. It's currently the only computer that is taking orders. It accesses a remote installation of NexoPOS. I installed as well a local version of NexoPOS on it that should be used for printing but couldn't make it work.
> 
> The printer that is connected to this computer should print receipts as well as kitchen orders.
> 
> We might take orders later from a mobile phone or tablet.
> 
> The remote installation has HTTPS. The local installation doesn't.
> 
> I'm using Gastro on the remote installation of course.
bro, i've been telling this for 1 year, i have 6 licenses, i gave so much money, i bought all the modules. Although we pay so much for the nexo print server, we can't use it properly. It requires constant approval on every device. If it is the waiter's phone, we will take the order, but it does not connect to printing with http, it connects with https. The room requires confirmation, which is a problem for my customers.

**Comment by josephelkhoury** [comment]
Personally, I'm confused because the documentation is not clear.

I paid for a license and I don't know where to use it.

What should I install where?
Which modules should be installed on the local installation?
Which ones should be installed on the remote installation?
Where should I enable HTTPS? Where shouldn't I?

@Blair2004 we need some help here plz 🙃

**Comment by lim10soft** [comment]
> Şahsen kafam karıştı çünkü belgeler net değil.
> 
> Bir lisans için para ödedim ve onu nerede kullanacağımı bilmiyorum.
> 
> Neyi nereye yüklemeliyim? Yerel kurulumda hangi modüller kurulmalıdır? Uzaktan kurulumda hangileri kurulmalı? HTTPS'yi nerede etkinleştirmeliyim? Nerede yapmayayım?
> 
> @Blair2004burada biraz yardıma ihtiyacımız var plz🙃

I will help you bro. Write to lim10soft@gmail.com or whatsapp 0850 466 8724

**Comment by Blair2004** [comment]
Hey, sorry for the late reply @josephelkhoury how is that going?

**Comment by Blair2004** [comment]
The issue is closed for inactivity. As a short note, we're about to have a window app that comes with Cloud Printing. this will enhance and improve the printing capabilities on NexoPOS 5
