### ISSUE TITLE
Printing using Epson TM-M30II & Ipad

### ISSUE THREAD

**Issue by salateeq** [Blair2004/NexoPOS#1562]
Describe the bug
I just uploaded Nexopos to my VPS. I tried to place an order using my windows laptop and everything went fine.However, when I use my Ipad, the Ipad couldn't find the printer. what is the work around
Replace this section with a clear description of your issue.

To Reproduce

Go to POS Main page
place an order and pay
printing dialog appears and the printer is not shown
Expected behavior
Printing receipt using Ipad

Environment:

NexoPOS [v4.8.19]
Premium Extensions:
<img width="754" alt="252736521-8dadadd1-26a4-453a-8d65-342401606bb3" src="https://github.com/Blair2004/NexoPOS/assets/19849656/e88d3296-0b73-40d4-9b06-c3af487d98b8">

**Comment by Blair2004** [comment]
Hi,
Your issue might be related to the fact the internet connexion is not
secure. Please est schedule an appointment for tomorrow so an agent can low
more closer for this (only for premium customer)

Let us know your email by email at ***@***.***

Kind regards.

**Comment by salateeq** [comment]
Hello

This is my email address, what time suits you for a meeting

Thanks
________________________________
من: Blair Jersyer ***@***.***>
‏‏تم الإرسال: 23/ذو الحجة/1444 09:19 م
إلى: Blair2004/NexoPOS ***@***.***>
نسخة: salateeq ***@***.***>; Author ***@***.***>
‏‏الموضوع: Re: [Blair2004/NexoPOS] Printing using Epson TM-M30II & Ipad (Issue #1562)


Hi,
Your issue might be related to the fact the internet connexion is not
secure. Please est schedule an appointment for tomorrow so an agent can low
more closer for this (only for premium customer)

Let us know your email by email at ***@***.***

Kind regards.

**Comment by salateeq** [comment]
Hello
Thank you for your support.
I am premium customer. Have you got my email?

**Comment by salateeq** [comment]
Hi

Regarding this issue https://github.com/Blair2004/NexoPOS/issues/1562
[https://opengraph.githubassets.com/3aadf6bc687464da3d24d6523df003e19786ae22b780fac898fa1f917315cb49/Blair2004/NexoPOS/issues/1562]<https://github.com/Blair2004/NexoPOS/issues/1562>
Printing using Epson TM-M30II & Ipad · Issue #1562 · Blair2004/NexoPOS<https://github.com/Blair2004/NexoPOS/issues/1562>
Describe the bug I just uploaded Nexopos to my VPS. I tried to place an order using my windows laptop and everything went fine.However, when I use my Ipad, the Ipad couldn't find the printer. what ...
github.com

**Comment by Blair2004** [comment]
Hey, did you receive any help from the support by email ?

**Comment by Blair2004** [comment]
Closed due to inactivity.
