### ISSUE TITLE
[Issue] provide a title for the issue you're facing here

### ISSUE THREAD

**Issue by raproos** [Blair2004/NexoPOS#1569]
Good day

I am having an issue installing NexoPOS-4.8.19 it keep on showing network error
![Capture](https://github.com/Blair2004/NexoPOS/assets/22525969/da4fa1b4-1a46-4615-86b0-9df77a56e733)
What can be the issue?

**Comment by Blair2004** [comment]
Your issue is not correctly formatted. Please read this #501 to understand how to create an issue.
