### ISSUE TITLE
[Issue] Nexopos 4.x can't run workers

### ISSUE THREAD

**Issue by iosc** [Blair2004/NexoPOS#1577]
**Describe the bug**
Workers Aren't Running

The workers has been enabled, but it looks like NexoPOS can't run workers. This usually happen if supervisor is not configured correctly.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'workers'
3. Scroll and click to 'test', then 'save settings'
4. refresh the browser and See error 'notification'

**Expected behavior**
Workers Aren't Running

The workers has been enabled, but it looks like NexoPOS can't run workers. This usually happen if supervisor is not configured correctly.

workers.log 0 byte, mysql ns_jobs and ns_failed_job all empty

**Screenshots**
<img width="1144" alt="Screenshot at Jul 28 10-36-01" src="https://github.com/Blair2004/NexoPOS/assets/4299695/5fae2db8-6c45-4b6a-b359-88f11ce8674e">

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]
 - Almalinux 9.1

**Comment by Blair2004** [comment]
Hi, this can be fixed using Laravel Queues: https://laravel.com/docs/10.x/queues

**Comment by iosc** [comment]
hi Blair,

Thanks for the reply. I am on Laravel 9.x, and tested Queue and Supervisord all configured correctly and tested in CLI too, but the nexopos dashboard still seeing the notification stating that nexopos was not configured correctly without any further indications on what is the error?

The main problem I am having is when in busy business hour (lunch hour), i.e. 6 to 7 out of 10 orders continuosly not printing to cashier, water bar or kitchen printers

So I have to try to run workers / queue in order to see if that is the issue causing print problem
