### ISSUE TITLE
[Issue] Install wizard not working properly. 

### ISSUE THREAD

**Issue by pneves001** [Blair2004/NexoPOS#1585]
**Describe the bug**
Setup process not completing 

**To Reproduce**
1. download nexopos from github repo. 
2. setup environment. 
3. Start the setup script. 
4. Provide database settings. 
5. provide account settings. 
6. allow the script to continue until the update migrations are run and it fails. 

**Expected behavior**
The site is expected to setup the database.  And then complete normally and finally allow me to log into the POS system with my account information. 

**Screenshots**
![Screenshot 2023-08-06 at 12 20 04 PM](https://github.com/Blair2004/NexoPOS/assets/1206722/f1207077-ee25-4789-bf74-69f5f12c15f7)

[2023-08-06 19:19:45] 127.0.0.1.ERROR: Attempt to read property "id" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /Users/philipneves/Documents/NevesSoftware/NexoPOS/database/migrations/update/2021_05_25_170640_update_default_payment_types.php:32)
[stacktrace]
#0 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', '/Users/philipne...', 32)
#1 /Users/philipneves/Documents/NevesSoftware/NexoPOS/database/migrations/update/2021_05_25_170640_update_default_payment_types.php(32): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Attempt to read...', '/Users/philipne...', 32)
#2 /Users/philipneves/Documents/NevesSoftware/NexoPOS/app/Services/UpdateService.php(100): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
#3 /Users/philipneves/Documents/NevesSoftware/NexoPOS/app/Services/UpdateService.php(51): App\\Services\\UpdateService->executeMigration('database/migrat...', 'up')
#4 /Users/philipneves/Documents/NevesSoftware/NexoPOS/app/Http/Controllers/UpdateController.php(40): App\\Services\\UpdateService->executeMigrationFromFileName('database/migrat...')
#5 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\UpdateController->runMigration(Object(Illuminate\\Http\\Request))
#6 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('runMigration', Array)
#7 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\UpdateController), 'runMigration')
#8 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#10 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/philipneves/Documents/NevesSoftware/NexoPOS/app/Http/Middleware/LoadLangMiddleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\LoadLangMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#20 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#21 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#22 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#23 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#24 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/philipneves/Documents/NevesSoftware/NexoPOS/app/Http/Middleware/ForceSetSessionDomainMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ForceSetSessionDomainMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/philipneves/Documents/NevesSoftware/NexoPOS/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /Users/philipneves/Documents/NevesSoftware/NexoPOS/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 /Users/philipneves/Documents/NevesSoftware/NexoPOS/server.php(19): require_once('/Users/philipne...')
#46 {main}
"} 

**Environment:**
 - NexoPOS 4.x vesrion: Latest version in the repo. nexopos-4x. 
 - Premium Extensions: none.

**Comment by Blair2004** [comment]
Hi, 
this error is caused (probably) because you're deploying NexoPOS using "php artisan serve".

This method is for now not recommended as that (development) server is frequently restarted when NexoPOS attempts to edit the .env file. After the setup page requires the application's details, when it's installing the tables, it's interrupted because of the file .env is edited during the process, causing some migrations tables to not run.

after a refresh, you're told the setup is no longer accessible meaning the setup is complete (which is not the case). When you attempt to log in, you land on a database migration page, which files because no administrator was defined during the setup process. That's why when NexoPOS (which assumes an admin exists) tries to get the administrator id, but that is not defined, so the migration fails.

**Solution**: Do not use php artisan serve, but instead a virtual server such as Laragon. If you're one ubuntu, wsl2, configure NexoPOS as recommended on the [documentation](https://my.nexopos.com/en/documentation/getting-started/configuring-the-environment).

**Comment by Viet80s** [comment]
Hi, can I have a question?
I have got the same issue. Thanks for the explanation and help but what do you mean by using a "virtual server such as Laragon". Can you please show me the steps to do that, if you can?
Thanks a lot.

**Comment by Blair2004** [comment]
> Hi, can I have a question? I have got the same issue. Thanks for the explanation and help but what do you mean by using a "virtual server such as Laragon". Can you please show me the steps to do that, if you can? Thanks a lot.

This should help https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon

**Comment by Viet80s** [comment]
Many thanks for that, @Blair2004 . Very helpful <3
