### ISSUE TITLE
[Issue] very urgent problem!!  Gastro sometimes makes 2 requests when you send a receipt to the kitchen. This causes 2 of the same order slips to come out and the chefs cook the food twice.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS#1589]
https://github.com/Blair2004/NexoPOS/assets/102427740/500db6f5-0601-43a5-8b58-a8739585d9ad

![WhatsApp Image 2023-08-07 at 13 24 21](https://github.com/Blair2004/NexoPOS/assets/102427740/cec7a230-9be4-4d9c-b24f-f1c6ffd5f5ba)

Gastro sometimes makes 2 requests when you send a receipt to the kitchen. This causes 2 of the same order slips to come out and the chefs cook the food twice.

gastro version:  v4.8.15 
nexopos version: 4.8.17
nps adaptör : v4.8.8

**Comment by lim10soft** [comment]
the source of the problem is caused by this file
 \modules\NsPrintAdapter\Resources\Views\pos


sendXMLPrintRequest({ printer, content, address }) {
        return new Promise( ( resolve, reject ) => {
            const loading   =   Popup.show(  );

            const oReq = new XMLHttpRequest();

const loading = Popup.show( );

            const oReq = new XMLHttpRequest(); If I remove these codes, the problem is solved. but this time it does not issue account slip.

**Comment by lim10soft** [comment]
'should_pixelize'       :   <?php echo ns()->option->get( 'ns_pa_convert_to_image', 'no' ) === 'yes' ? 'true' : 'false';?>,
  I 

completely removed this code, the problem seems to be solved

**Comment by iosc** [comment]
hi ya, I have this similar issue 

but mine is printing on cashier, water bar and kitchen

business is busy especially on lunch time, i.e. 3 out of 10 orders, there are always missing printing on water bar OR kitchen printer

the only errors that may caused the iisue maybe the ERROR red internal server error 500 appear in web console for

.../api/print:1

<img width="1275" alt="image" src="https://github.com/Blair2004/NexoPOS/assets/4299695/d3a1fce1-dabd-4384-ba4f-e795521a6546">

**Comment by lim10soft** [comment]
they do not deal with the problems, unfortunately, I came up with the solution myself. but they know how to get paid, they leave their work half done. If you are using nps adapter 4.8.8 replace this file with the one I provided.

C:\laragon\www\modules\NsPrintAdapter\Resources\Views\pos

[footer.blade.zip](https://github.com/Blair2004/NexoPOS/files/12321130/footer.blade.zip)

**Comment by lim10soft** [comment]
Don't try to dare to update, because even though I mentioned the most recent gastro problem, they didn't solve it. There are problems such as the cart not being reset officially when adding to the ticket. they are not interested. We write something, we get a reply after 1 month. Even though we took a video in the reply I received, we did not understand the problem. they give an update they break 10 things.

**Comment by Blair2004** [comment]
This issue is caused by Gastro not being updated. 
You should note that from the latest version of Nexo Print Adapter, that module is taking off printing capability for every other module. So if you're using an older version of Gastro and still handling printing, you'll have 2 prints in the kitchen.

So in sum, the error is caused for mixing old and new modules on the same installation. Regardless, we're sorry for the delay in our response at the moment.

**Comment by iosc** [comment]
> they do not deal with the problems, unfortunately, I came up with the solution myself. but they know how to get paid, they leave their work half done. If you are using nps adapter 4.8.8 replace this file with the one I provided.
> 
> C:\laragon\www\modules\NsPrintAdapter\Resources\Views\pos
> 
> [footer.blade.zip](https://github.com/Blair2004/NexoPOS/files/12321130/footer.blade.zip)

hi lim10soft

Thank you for your sharing!!! I will wait for the customer restaurant day off on next wednesday to try out your files (^_^)

It's really a waste not to get this pos doing good ;) Most of the parts already doing well but they stop us to help improving by feedback the bugs

Once the POS been perfect then they can easily earn more instead

Let me try out the fix first. Thanks a lot again

**Comment by iosc** [comment]
> Don't try to dare to update, because even though I mentioned the most recent gastro problem, they didn't solve it. There are problems such as the cart not being reset officially when adding to the ticket. they are not interested. We write something, we get a reply after 1 month. Even though we took a video in the reply I received, we did not understand the problem. they give an update they break 10 things.

I got the similar situation and issues like you too

The only way to solve is using our experiences and study their code to fix many bugs, this is quite time wasting because the documentation is really not helpng much though

I will have to makes a lot of the backup to fix things one by one, especially now the client is facing receipt not printing in high percentage, especially when the business is busy

**Comment by lim10soft** [comment]
> This issue is caused by Gastro not being updated. You should note that from the latest version of Nexo Print Adapter, that module is taking off printing capability for every other module. So if you're using an older version of Gastro and still handling printing, you'll have 2 prints in the kitchen.
> 
> So in sum, the error is caused for mixing old and new modules on the same installation. Regardless, we're sorry for the delay in our response at the moment.

I have already pointed out to you that the most recent version of gastro and nexopos is faulty. there are a lot of errors. Especially when adding a second product to the ticket, the cart is not reset. There are errors like this. I took the video, but you didn't even look at it. Not used because the latest version is faulty.

**Comment by lim10soft** [comment]
https://github.com/Blair2004/NexoPOS/issues/1514 I checked to see if this problem has been resolved to upgrade to the latest version, but we are still not resolved.

**Comment by Blair2004** [comment]
With no proper details on the modules and version used, this issue can't be handled.

**Comment by lim10soft** [comment]
If you download and try your latest version, you will see that the basket is not reset and it does not send a receipt to the kitchen.
