### ISSUE TITLE
[Issue] Too few arguments to function 1 passed and exactly 2 expected

### ISSUE THREAD

**Issue by faytranevozter** [Blair2004/NexoPOS#1595]
**Describe the bug**
Error on adding hook addFilter

**To Reproduce**
1. Add module
2. Add service provider file
3. Add hook
```php
<?php
namespace Modules\Yureka\Providers;

use App\Classes\Hook;
use App\Classes\Output;
use Illuminate\Support\ServiceProvider as CoreServiceProvider;

class ProductProvider extends CoreServiceProvider
{
    /**
     * register method
     */
    public function register()
    {
        Hook::addFilter('ns-crud-footer', function (Output $output, $namespace) {
            if ($namespace === 'ns-products') {
                $output->addView('Yureka::footer');
            }

            return $output;
        });
    }
```
i got from [here](https://my.nexopos.com/en/documentation/filters/namespace-crud-actions)
4. Got error too few arguments
<img width="1132" alt="image" src="https://github.com/Blair2004/NexoPOS/assets/16716664/f145fcd1-4739-449a-8193-4812098bb0e0">

**Expected behavior**

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.19
 - PHP 8.2.9

**Comment by Blair2004** [comment]
The addFilter method accepts as third parameters how many parameters are accepted by the callback. You'll therefore need to explicitly add a third parameter with 2 as a value.
