### ISSUE TITLE
[Issue] "Network error" shown when configurate the NexoPOS for the first time

### ISSUE THREAD

**Issue by Viet80s** [Blair2004/NexoPOS#1602]
**Describe the bug**
After setting everything similar to this video https://www.youtube.com/watch?v=-eXapKZrcBc (How To Download And Install NexoPOS 4.x On Windows 10), I managed to access the Dashboard for the first time. There were two steps and I passed the first one (which is set up the Database), but the second one, when I tried to create an Application, I couldn't process it. A red notification popped up saying that "Network Error". So I am stuck. Please help me! 

**To Reproduce**
1. I extracted the NexoPOS Zip file to my laragon/www/NexoPOS-master folder
2. Run "composer install" then "php artisan key:generate" then "php artisan  storage:link"
3. Run "php artisan serve" then go to [http://127.0.0.1:8000]
4. Go to Dashboard - completed the first step
5. Stuck in the second configuration step

**Expected behavior**
Normal landing or login page shown up

**Screenshots**
![Screenshot 2023-08-16 204647](https://github.com/Blair2004/NexoPOS/assets/137057864/63884831-b06d-4dca-9253-43573ae36a30)

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.19
 - Premium Extensions: n/a

**Comment by Viet80s** [comment]
I tried to restart the Laragon + create another MySQL database, then right-click on Laragon, choose the app (instead of using php artisan serve), and now it works well.
Just put here my sown solution for anyone have a similar error in the future. Cheers!

**Comment by Blair2004** [comment]
Hey,
Try using the v5 branch https://github.com/Blair2004/NexoPOS/tree/v4.5.x
using "php artisan serve", NexoPOS changes the .env file which causes the server to restart... and therefore to the ongoing request to fail (Network error). We've improved the support with PHP artisan serve on the branch 5

**Comment by Viet80s** [comment]
thanks a lot @Blair2004 . I will try it

**Comment by dekarpaulvictor** [comment]
@Blair2004 thank you for your work and the effort you put into this. Isn't the latest version of the software supposed to be a better version than one from an "earlier branch"? Why would reloading the environment trigger a "network error" and prevent someone from completing the setup process if everything checks out, i.e. all required input is correctly entered? If using `php artisan serve` is not recommended, what is? How do you actually install this app and start using it?

**Comment by Blair2004** [comment]
Hi,

@dekarpaulvictor this should point you in the right direction: https://github.com/Blair2004/NexoPOS/issues/1585#issuecomment-1681382430

Reloading the environment automatically restarts the server... that's how PHP artisan serve was made. If the server restarts it has to stop first so it triggers the error if there is an ongoing request.

You might consider using NexoPOS 5x which was made to be compatible with PHP artisan serve.

**Comment by dekarpaulvictor** [comment]
Hi @Blair2004, thanks for your response. What if I don't want to use Laragon to install NexoPOS? I assume it's a Windows-only application? I'm on Linux. Let me give NexoPOS 5 a shot and report my findings. Thanks once again.

**Comment by dekarpaulvictor** [comment]
I found a temporary solution for now, just to get me through the Application Setup stage. One can pass the `--no-reload` option to `php artisan serve` to stop it from reloading the "development server on .env file changes". This helped me complete the installation process. Now I can sign in and continue exploring NexoPOS's features. Thank you.

**Comment by ZohaibTafsol** [comment]
hi @Blair2004 are project is pretty awesome I want to know that how could I run your project in my machine because I have so much issue to run that project on my machine. Waiting for your response .

**Comment by Blair2004** [comment]
@ZohaibTafsol what type of issue are you facing ?

**Comment by Blair2004** [comment]
Closed for inactivity
