### ISSUE TITLE
[Issue] Super long (more than 1 meter) receipt prints when print by 2nd loggedin user

### ISSUE THREAD

**Issue by iosc** [Blair2004/NexoPOS#1604]
**Describe the bug**
Describe the bug
All updated to the latest up to date nexopos v4.8.19, with gastro v4.8.20, nps v4.8.8, nexo print server beta on laragon

NexoPOS is hosted on Linux server

1st main user logged in and operating nexopos smoothly, including printing OK.

While 2nd user logged in on another pc/mobile device and start operating, with everything went on smoothly, BUT when 2nd user try to print whatsoever, there always printed super long (more than 1 meter) receipt prints where just all junk ASCII code

(There are 3 printers, Cashier, WaterBar, Kitchen, all running on cat-6 network cables connected to Windows 10 64 bit PC using laragon nexo print server)

**To Reproduce**

1. Main user logged in to POS --> operating as usual
2. Any 2nd user  logged in to POS on another client PC/Mobile device using --> operating as usual
3. When 2nd user try to do any types of printing on POS/Dashboard --> any selected print will print super long (more than 1 meter) receipt prints where just all junk ASCII code
4. See screenshots error

**Expected behavior**
print super long (more than 1 meter) receipt prints where just all junk ASCII code

**Screenshots**
![4610D6F7-2F80-40AD-A493-CCFB2E5F174C_1_102_o](https://github.com/Blair2004/NexoPOS/assets/4299695/df5b82f3-47b3-4485-a66d-1e1bfaad5ecd)
![A82747F5-431F-4C85-AA70-FDCCBBE4F62C_1_102_o](https://github.com/Blair2004/NexoPOS/assets/4299695/7481e2cd-4adb-45a3-98cb-a7044c97ba47)
![8F6F6795-95A1-48BC-906E-C8B930793FB7_1_102_o](https://github.com/Blair2004/NexoPOS/assets/4299695/9a7541da-1b30-45c4-9dc0-235a837d6a9f)
![264E2927-089E-4AD4-8200-F85BF0557C2C_1_102_o](https://github.com/Blair2004/NexoPOS/assets/4299695/753001c5-5e8f-4f82-a737-3ed33e8b77e4)

**Environment:**
- NexoPOS 4.x vesrion: [4.8.19]
- Premium Extensions: [ Gastro (4.8.20) ]
- Premium Extensions: [Nexo Print Adapter (4.8.8), Gastro (4.8.20)]

**Comment by lim10soft** [comment]
this problem seems to be related to your printer

**Comment by iosc** [comment]
Hi lim10soft

my 3 printers working good everyday BUT this happened only while. Anyone logged in at the same time and did any prints will have the issue, if the other first logged in user prints still good 😅

I wonder is that caused by image printing caused the second user in parallel not able to print as image?

We need image printing due to Chinese Asian characters is a must

Can you 2 users print parallels normally? I remember you did print Turkish text too, right?

**Comment by nzian** [comment]
It might be cause for any special character that not supported by your printer? Could you check very carefully is there any... and also in the comment section I found talking about image printing. it also might be a reason to print scramble character as well. I dont think 3 or more user is the reason. Reason is encoding of the printed content and the printer support that encode or not. If you share the order content and printer name, model then it will be more helpful to find out.

**Comment by iosc** [comment]
hi nzian, thank you for the comment 

hi all,

1) Print as image is needed because we have Chinese utf-8 character in menu and that is a MUST ;)

2) Currently every operations, display, printing receipt ALL working perfectly since 10-April-2023 till now (6-September-2023) for the First administrator user Cashier1, printing near 100 receipts everyday

user WaterBar and user Kitchen only use Gastro to view "Kitchen Screen" running well on 10 inches Android Tablets EXCEPT printing (tested same issue printing "long recipts with scrambled text" but these users we DO NOT need printing

3) The 3 printers brand and model are exactly the same, china made general receipt printer used by most of the retailers in Malaysia printing English, Chinese, Tamil etc multi-languages printer, and we did able to print correctly everyday now, BUT it is just having problem for any other users to print long garbage scrambled text other then the "Main Admin user"

4) That is why i reported here and wish Nexopos creator to test for us so then can find out if the print encoding and print as image is possible for 2nd user onwards. Today i tested with main admin user logged out has the same issue.

5) Just tested again on GMT+8 7-September-23 now, I re-save again on all the nexopos dashboard options as the same for the daily main administer (which we use it everyday for months) but still cannot print normally

i created NEW user and tested with different store admin role, waiter role etc  but still cannot print normally

I even logged out the daily main administer with new user as administrator logged in, but still cannot print normally

check all the mysql/mariadb and found the daily main administer and all the other users, they are all looks have the same attributes

For summary, now the daily main administer "CAN / ABLE" to print normally and operated perfectly, *BUT* any other users cannot print (long print with scrambled text) BUT can operate smoothly

**please try your side if can print by 2 different users at the same time?**

Hopes to get issue solved, Thank you

**Comment by iosc** [comment]
UPDATES!!!

Today i did tried a few more different situations and got some goods BUT still not find the solutions yet though 

1) We tried on Window 10 on Honor brand i5 laptop using chrome to logged in as 2nd user, print job works!!! but just minor part need to tune, where printing is 20% to 30% larger (see attachments)

2) on my mi macbook air and iphone 14 max STILL printing scrambled long receipt while the daily used Main M2 Mac Mini is still printing good, even i use other user account it prints good.

Weird things now is all this Apple products have no printers installed on them.

3) So now i almost confirm that this issue is more on network printing drivers or etc problem.

I will test more, if once resolved then will update all

**Comment by Blair2004** [comment]
Alright, feel free to revert back on any progress
