### ISSUE TITLE
[Issue] Having issue on installing/setting up the nexoPOS from git clone

### ISSUE THREAD

**Issue by ZohaibTafsol** [Blair2004/NexoPOS#1605]
![image](https://github.com/Blair2004/NexoPOS/assets/134605543/d3779cbe-bf08-4ade-9b7d-2fe68c137fdc)

Unable to locate Mix file: /js/bootstrap.min/bootstrap.js.
Kindly give the line by line installing process so everyone could install it properly.

commands I ran is after clone.

- composer install --ignore-platform-req=ext-gd   // its give me sort of error to avoid the extension error is use --ignore-platform-req=ext-gd 
- npm install
- php artisan storage:link
- npm run watch
- php artisan serve

no clue why I'm facing error.

**Comment by Blair2004** [comment]
Hi,
You don't need to either run "npm install" or "npm run watch".... you don't need that.
You should use it if you're about to customize the assets, so you'll need to know how Laravel mix works. 

You'll need to reinstall NexoPOS as "npm run watch" clears the compiled assets. If you still want to build NexoPOS assets you should run "npm run prod" instead.

**Comment by Blair2004** [comment]
closed for inactivity
