### ISSUE TITLE
[Issue] Error installing NPS Adapter v4.8.8

### ISSUE THREAD

**Issue by pachidj87** [Blair2004/NexoPOS#1623]
**Describe the bug**
After installing and setup NexoPOS v4.x from github I installed NPS Adapter and the system throw this error
**An Error Occurred "NPS Adapter": Class "Modules\NsGastro\Crud\KitchensCrud\" not found**

**Environment:**
 - NexoPOS 4.x version: 4.8.21
 - Premium Extensions: Nexo Print Adapter (4.8.8) from Github source

**Comment by Blair2004** [comment]
Hi,
Thank you for pointing that. In fact, it seems like the module was downloaded from an unmaintained repository.
Please make sure to use the premium version available on our [marketplace](https://my.nexopos.com/en/marketplace/item/nps-adapter-for-nexopos-4x)

Kind regards
