### ISSUE TITLE
Account Transaction when cashier processing order

### ISSUE THREAD

**Issue by gurulancer** [Blair2004/NexoPOS#1628]
I am trying to add fund in account transaction while processing order as a cashier. but I got "_**Not enough permission**_" message
How to give this permission to cashier ?
[ am going to use this function for adding gift card amount. I am going to selling gift card in online community site store to visitors.
and after purchasing, they visit store and place order with the purchaed gift card.
Is there any idea to redeem gift card when placing order ?

**Comment by Blair2004** [comment]
Hey,
Can you screenshot where you're having this error? We tried to fund customer wallet from our end and it worked.
Thanks

**Comment by gurulancer** [comment]
Here is the screen shot
![cashier=account-transaction-permission-issue](https://github.com/Blair2004/NexoPOS/assets/132946315/59325c23-0b9e-42da-9af0-76e0e2d29dd7)
I give all permission as you mentioned in whatsapp. But Still, I cannot do

**Comment by Blair2004** [comment]
Hey, we're currently requesting the screenshot having the error message. Here we can see the permissions manager screen.

**Comment by gurulancer** [comment]
Okay Here
![cashier-account-transaction-permission-issue-1](https://github.com/Blair2004/NexoPOS/assets/132946315/8502b653-edd2-4036-bbee-c97cef0b0119)

**Comment by gurulancer** [comment]
Did you check ?

**Comment by gurulancer** [comment]
it's been 2 weeks almost
Please check and fix

**Comment by Blair2004** [comment]
Hi,
Make sure to enable this permissions especially (note that there are two with the same name, you can enable both).

![image](https://github.com/Blair2004/NexoPOS/assets/5265663/bff035db-6678-464d-a883-2419a691d0da)

It should be working. If it doesn't work, feel free to comment.

**Comment by Blair2004** [comment]
Hi,
Make sure to enable this permissions especially (note that there are two with the same name, you can enable both).

![image](https://github.com/Blair2004/NexoPOS/assets/5265663/bff035db-6678-464d-a883-2419a691d0da)

It should be working. If it doesn't work, feel free to comment.

**Comment by gurulancer** [comment]
of course, the both are enabled..but still it is not working
Check please

**Comment by gurulancer** [comment]
Why did you close this issue while still it is not working ?

**Comment by gurulancer** [comment]
Really appreciate
