### ISSUE TITLE
cant install nexopos 4.8.21

### ISSUE THREAD

**Issue by Noorhad** [Blair2004/NexoPOS#1647]
cant install it on https://sparkbazar.com/pos/. cant find a index. please help

**Comment by nzian** [comment]
https://my.nexopos.com/en/documentation/getting-started/download-and-install
https://my.nexopos.com/en/documentation/how-tos/how-to-install-nexopos-from-the-cpanel
https://my.nexopos.com/en/documentation/how-tos/how-to-install-nexopos-from-the-cpanel
I hope you already visit above link. if not then check those. if you still failed then let me know. @Noorhad 
Thank you

**Comment by Blair2004** [comment]
Closed for inactivity.
