### ISSUE TITLE
[Issue] Update error v4.8.21

### ISSUE THREAD

**Issue by gurulancer** [Blair2004/NexoPOS#1650]
**Describe the bug**
Try to update from v4.8.17 to v4.8.21

I got this error

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.8.17]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.8.15)]
![UPDATE-ERROR](https://github.com/Blair2004/NexoPOS/assets/132946315/b3a1ddd9-2364-4457-86e5-ad5325d13f99)

**Comment by Blair2004** [comment]
Hi,
It appears like the .exec function is disabled on your environment. Nexo Updater requires to have access to that feature to download and execute updates.

**Comment by Blair2004** [comment]
Closed for inactivity.
