### ISSUE TITLE
NexoPOS 4-Database Update issue

### ISSUE THREAD

**Issue by reazulhaque20** [Blair2004/NexoPOS#1660]
While installation of NexoPOS 4, at the stage of database update, it's showing "Attempt to read property "id" on null".
After several try no luck.
![Screenshot 2023-11-06 001120](https://github.com/Blair2004/NexoPOS/assets/37473674/8e140556-a4dd-4b3c-9e8e-c28f7e7ff7aa)

**Comment by Blair2004** [comment]
If you're using `php artisan serve` that's the reason... NexoPOS 4x doesn't works well with that virtual server. consider using this tutorial https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon

**Comment by Blair2004** [comment]
Closed for inactivity.
