### ISSUE TITLE
[Issue] 404 on any link after new installation

### ISSUE THREAD

**Issue by privateer00** [Blair2004/NexoPOS#1665]
**Describe the bug**
After a new installation i can reach the first page but i get error 404 on every link.

**Screenshots**
![image](https://github.com/Blair2004/NexoPOS/assets/84980482/b50bdbbd-4a2c-453f-afba-f59fa03565b8)
![image](https://github.com/Blair2004/NexoPOS/assets/84980482/dcb8e882-c34e-4418-9151-d23a8e0f5f5b)

**Environment:**
 - NexoPOS 4.8.21
 - ubuntu 22.04
 - tutorials followed step by step, nexopos installed with Packagist method in /var/www/nexopos-4x

here the config file for apache virtualhost

`  
<VirtualHost *:80>
    #ServerName 10.200.200.10
    #ServerAlias  www.10.200.200.10
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/nexopos-4x/public
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`

**Comment by Blair2004** [comment]
Hi,
Can you make sure the "mod_rewrites" module exists on your environment. You can check it's the cause if using your IP address + /index.php/dashboard opens the actual dashboard.

Let us know.

**Comment by Blair2004** [comment]
Closed for inactivity
