### ISSUE TITLE
Blank only logo Installation not setup database

### ISSUE THREAD

**Issue by herybrts** [Blair2004/NexoPOS#1695]
Hi nexopos, I'm currently trying to install nexopos on my VPS. I use the control panel from aapanel. And I have installed composer and laravel 9 and php using version 8.1.

I have now downloaded the nexopos file from GitHub and extracted it to my www diaapanel. The next stage I have carried out the composer install process.

when I opened my domain it turned out that Failed to open stream: Permission denied appeared, 

![3](https://github.com/Blair2004/NexoPOS/assets/115608706/7c9a419b-a6cc-4faf-bd98-331cbccdc4f0)

![4](https://github.com/Blair2004/NexoPOS/assets/115608706/350051e5-e056-4369-ac29-38d57ddbe97a)

then I did php artisan cache:clear

when I reopened my domain this image appeared

![1](https://github.com/Blair2004/NexoPOS/assets/115608706/3072fb34-0801-443b-aadb-678a81e8cc88)

then I clicked all the dashboard buttons, signin, signup then it was directed to mydomain/public/do-setup. In this process, only the logo appears and there is no database installation wizard form and others.

![2](https://github.com/Blair2004/NexoPOS/assets/115608706/fc035ff2-ab0a-46d3-8b12-7162ea4d3ff7)

If I use composer install again on my VPS terminal, the error message denied permission will appear again

Is there something wrong with my installation process?

My VPS uses:
Apache 2.4
PHP 8.1.26
PHP CLI 8.1
Laravel 9.52.7
MySQL 5.7.34
Composer 2.6.6

**Comment by Blair2004** [comment]
Hi,
Can you share the console log when only the logo appear (it's usually F12, then search "Console" tab)

**Comment by herybrts** [comment]
thankyou for reply Blair2004..

this is my console error

![error](https://github.com/Blair2004/NexoPOS/assets/115608706/727ed2e3-b999-4894-9e9f-6cadad080c28)

**Comment by Blair2004** [comment]
Hi, sorry for the late reply (holiday happening). How is that going ?
