### ISSUE TITLE
[Issue] "Submit payment" button not updating automatically on v5.0.0

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1707]
**Describe the bug**
The "submit button" is not being updated automatically when we add a new payment on the payment popup.
In order to update, we need to switch from a payment type to another so that the button becomes visible.

**To Reproduce**
Add any item to the cart.
Click on the payment button to open the payment popup.
Enter the amount of the order and enter. 
The "submit payment" button doesn't appear.

**Expected behavior**
It should appear once the tendered amount is equal or higher to the order total value.

**Screenshots**
<img width="1721" alt="Screenshot 2024-01-09 at 6 34 43 PM" src="https://github.com/Blair2004/NexoPOS/assets/1782788/23d500f9-7eef-450b-a09b-37d324bb2121">

**Environment:**
 - NexoPOS vesrion: 5.0.0

**Comment by Blair2004** [comment]
Hi, do you mean the "Layaway" button should be turned into "Submit Payment" ?

**Comment by josephelkhoury** [comment]
> Hi, do you mean the "Layaway" button should be turned into "Submit Payment" ?

Yes this is how it was done in the 4.x.x versions. 
It's currently happening but only if you change the payment gateway and get back to the previous one.
It means "refreshing" is not happening automatically.

**Comment by Blair2004** [comment]
Yes, i've spotted the issue. It's a reactivity issue. Thank you @josephelkhoury

**Comment by josephelkhoury** [comment]
It's now working perfectly (Y)
