### ISSUE TITLE
[Issue] Reset Functionality not working (Bug)

### ISSUE THREAD

**Issue by kunalbedi** [Blair2004/NexoPOS#1710]
**Describe the bug**
Reset functionality not working (5.x)

**To Reproduce**
1. Go to Settings> Reset
2. Choose Wipe Plus Grocery and have the create sales and create procurements tick boxes checked.
3. On submission, a message comes "The form has been saved successfully". 
4. Nothing runs and reset is unsuccessful

**Expected behavior**
Database should be truncated and populated with sample data.

**Environment:**
 - NexoPOS vesrion: 5.0.0

**Comment by kunalbedi** [comment]
Can you tell me how? Which console are you referring to.
I have made a screen recording of what is happening.
[https://app.screencast.com/Yv8eYiQxupsvV](url)

**Comment by Blair2004** [comment]
When you open that page (on Windows you click F12 on Mac it's Option+Command+I)
![screenshot-nimbusweb me-2024 01 10-12_37_24](https://github.com/Blair2004/NexoPOS/assets/5265663/365e1a28-6162-43c1-9601-db6aed51bf21)

**Comment by kunalbedi** [comment]
Here you go....

[https://app.screencast.com/gI72VELJVnkPU](url)

**Comment by kunalbedi** [comment]
Any update?

**Comment by Blair2004** [comment]
Using Chrome we're not able to reproduce this. The video seems no longer accessible. What browser are you using ?

**Comment by kunalbedi** [comment]
firefox
________________________________

**Comment by Blair2004** [comment]
> firefox Pleae copy the url and then see the video. Not sure why the link is not working if clicked directly. https://app.screencast.com/Yv8eYiQxupsvV and https://app.screencast.com/gI72VELJVnkPU

Just to know, by any chances, have you tested on another browser ?

**Comment by kunalbedi** [comment]
Tested on Chrome too. No joy!

**Comment by kunalbedi** [comment]
> > firefox Pleae copy the url and then see the video. Not sure why the link is not working if clicked directly. https://app.screencast.com/Yv8eYiQxupsvV and https://app.screencast.com/gI72VELJVnkPU
> 
> Just to know, by any chance, have you tested on another browser?

Tested on Chrome too. No joy!

**Comment by Blair2004** [comment]
This is what happens when I'm testing on Firefox 

![image](https://github.com/Blair2004/NexoPOS/assets/5265663/59c2e2e5-7243-4188-a31d-4bdbf1829a87)

I'm curious to see that bug live, ping me on WhatsApp at +14242314091

**Comment by kunalbedi** [comment]
Let me reinstall everything from source again and see if I can replicate it still... and then I will ping

**Comment by kunalbedi** [comment]
Any further update as per our chat on Whatsapp and the new video shared?

**Comment by kunalbedi** [comment]
Hi, Tested 5.0.1 version and it suffers the same issue.
If do not 
`npm install && npm run build`
The reset functionality works. 

If we do
`npm install && npm run build`
The reset functionality does not work.

I compared the reset.vue produced code after the npm buiild step and the bundled reset compiled code. There is inclusion of Tax.js in the newly compiled code. 
Just listing out things which may be helpful


FYI

**Comment by kunalbedi** [comment]
Demo works. but as I said, compiling assets sets the functionality to not work.

**Comment by Blair2004** [comment]
So just running : npm run build… it’s weird as that’s what is done before
each release.

If your system is online, let me know the credentials so I can check it
out. Let us know via ***@***.***

Kind regards

**Comment by Blair2004** [comment]
No update ? The email is contact(at)nexopos(dot)com

**Comment by kunalbedi** [comment]
Hi ,
There has to be an issue in my setup because the thing is illogica that compiling JS will break functionality. I will research some more using plain vanilla setup and see if I can replicate issue else will contact you over email ASAP.

**Comment by Blair2004** [comment]
Feel free to reopen the thread if the issue persists.
Kind regards.

**Comment by kunalbedi** [comment]
I am reopening this thread.

Environment
Node 20.11
Windows 11 Insider Buold 
PHP 8.2.12

Problem Description
The reset functionality breaks when running 'npm run build' and compiling the assets.
Please note that nothing is changed on the source code.
If we install and run reset, it works but does not after compiling.

Regards
Kunal Bedi
