### ISSUE TITLE
[Issue] Printing dircetly to recipt printer 

### ISSUE THREAD

**Issue by ahmedtohamy1** [Blair2004/NexoPOS#1753]
**Describe the bug**
Currently i moving from old vb.net app i use for pos to urs one, but there is some option i miss which is when i press print anyway it prints directly without any popups from chrome or browser
also may i have a guide to deploy app on pc locally without internet access?
(sorry for my bad knowledge in laravel)

**Comment by Blair2004** [comment]
Hi, thank you for your interest, this is more a general question about the app than an actual issue/bug. We have indeed many guides available on my.nexopos.com/en/documentation. To cite few of these we have:

- [Install NexoPOS On CPanel](https://my.nexopos.com/en/documentation/how-tos/how-to-install-nexopos-from-the-cpanel)
- [Install NexoPOS on Laragon Windows](https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon)

Regarding printing, you might use the kiosks mode, however, we recommend you to use [Nexo Print Server](https://my.nexopos.com/index.php/en/marketplace/item/nexo-print-server) which has a free option where you can print locally.

For further questions, note that you can reach out via email as well (contact@nexopos.com).
