### ISSUE TITLE
[Issue] Deleting a product from the cart

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1783]
**Describe the bug**
When you delete a product from the cart, it always deletes the last product on the list instead of the one you deleted.

**To Reproduce**
1. Open the POS screen
2. Select product 1, product 2, product 3.
3. Delete product 2.
4. Product 1 gets deleted.

**Expected behavior**
The product you clicked on should be deleted.

**Environment:**
 - NexoPOS version: 5.0.1

**Comment by Blair2004** [comment]
Hi, thank you for reporting.

**Comment by josephelkhoury** [comment]
Fixed, thanks (Y)
