### ISSUE TITLE
dashboard widgets dose not show

### ISSUE THREAD

**Issue by ameen-alshareif** [Blair2004/NexoPOS#1785]
**Describe the bug**
there are
![Screenshot 2024-02-23 154726](https://github.com/Blair2004/NexoPOS/assets/65165203/a469fc83-45c4-44cf-ada8-4a14885a49e8)
 there are no widgets on the dashboard screen

**To Reproduce**
1. Go to 'dashboard'

**Expected behavior**
widgets

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [e.g. 5.0.4]

**Comment by ameen-alshareif** [comment]
I fix it by replacing the public/build folder from my old 5.0.2 project

**Comment by Blair2004** [comment]
I believe the issue is fixed
