### ISSUE TITLE
cant delete stock-flow-records 

### ISSUE THREAD

**Issue by ameen-alshareif** [Blair2004/NexoPOS#1786]
**Describe the bug**
can't delete a stock record

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'stock-flow-records'
3. select a product and Click on  'option'
4. click delete See the error 
The GET method is not supported for route API/crud/ns.global-products-history/1. Supported methods: PUT, DELETE.

**Expected behavior**
delete record
![Screenshot 2024-02-23 175546](https://github.com/Blair2004/NexoPOS/assets/65165203/4443667a-55e3-4370-b612-3773364ce6ea)

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [5.0.4]

**Comment by Blair2004** [comment]
However, we'll make sure the error doesn't appear.

**Comment by Blair2004** [comment]
The feature was removed on v5.2.0
