### ISSUE TITLE
[Issue] no products found in stock adjustment 

### ISSUE THREAD

**Issue by ayoub-hs** [Blair2004/NexoPOS#1820]
**To Reproduce**
1. Go to 'stock adjustments'
2. Click on 'search field and type product name'
3. you'll get "Looks like no valid products matched the searched term." error

**Environment:**
 - NexoPOS vesrion: 5.1.1

**Comment by Blair2004** [comment]
Hi,
Products needs to be eligible for an adjustment. For instance non grouped product or product with stock management disabled are eligible.

**Comment by ayoub-hs** [comment]
thank you i enabled stock management and it works now.
