### ISSUE TITLE
database not being created

### ISSUE THREAD

**Issue by web-developer032** [Blair2004/NexoPOS#1836]
when trying to setup nexopos, it asked for the database configuration so I gave this name nexopos_v4 and type is utf8mb4_0900_ai_ci
now after connected to database its asked for the application I gave username and password then it gave me this error

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (Connection: mysql, SQL: alter table `ns_telescope_entries` add index `ns_telescope_entries_family_hash_index`(`family_hash`))

**Comment by Blair2004** [comment]
Hi, for upcoming issues, make sure to use this format #501
Now, what database are you using and what's the version you're using.

**Comment by Blair2004** [comment]
Closed for inactivity.
