### ISSUE TITLE
[Issue] I got error when create a new Procurement but the data was saved

### ISSUE THREAD

**Issue by candrasaputra** [Blair2004/NexoPOS#1846]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
1. go to New Procurement
2. Input Procurement Name and all detail
3. Open products tab
4. Add a product
5. Choose tax
6. Don't choose convert. (i don't want convert the unit)
7. You will see an error. the error message is like this: **The source and the destination unit can't be the same. What are you trying to do ?**
8. Go to Procurement Products List. (Even you got error, the data successfully saved)

**Expected behavior**
1. Is it possible to create a new Procurement without convert the unit?
2. if it not possible so, saving data should be failed because i got an error.

**Screenshots**
<img width="1792" alt="Screenshot 2024-04-08 at 02 12 30" src="https://github.com/Blair2004/NexoPOS/assets/9255677/8e2362c2-bdc8-4294-a8b8-823d4245177e">
<img width="1792" alt="Screenshot 2024-04-08 at 02 12 44" src="https://github.com/Blair2004/NexoPOS/assets/9255677/aff953e2-79e8-4e67-a2c3-a37620a6aa64">

**Environment:**
 - NexoPOS vesrion: [v5.2.1](https://github.com/Blair2004/NexoPOS/releases/tag/v5.2.1)
 - Premium Extensions: N/A

**Comment by Blair2004** [comment]
Hi,
thank you for reporting. We're checking this out.

**Comment by Blair2004** [comment]
Hi, can you consider sharing how the product is configured ? If you can provide a screenshot of the unit part (while editing the product).

**Comment by Blair2004** [comment]
This issue is caused by the assignation of the same unit to the product unit and the conversion unit.

![screenshot-nimbusweb me-2024 04 08-18_59_31](https://github.com/Blair2004/NexoPOS/assets/5265663/c537bca8-739e-40b4-84b9-3cebb485bcdc)

Make sure both are different. NexoPOS will prevent this in v5.2.2
