### ISSUE TITLE
[Issue] error without message in setup nexo pos

### ISSUE THREAD

**Issue by omega925** [Blair2004/NexoPOS#1849]
**Describe the bug**
I try to setup nexo pos after fill all information related to database connection and try to save setting it show me the red warning without any massage i try in local host and in real host but still same 

**To Reproduce**
I was enter information of connection database but it show me red warning without massage 

**Screenshots**
![Screenshot 2024-04-10 at 6 33 11 PM](https://github.com/Blair2004/NexoPOS/assets/29496590/abb5b842-325f-42c4-91e8-f13c89ba4711)

**Environment:**
 - NexoPOS vesrion: [e.g. 5.2.1]

**Comment by nexopos** [comment]
Hi, can you check the log file ? It's located on storage/logs
Thanks

**Comment by Blair2004** [comment]
Closed for inactivity.
