### ISSUE TITLE
The sales tax does not seem to work.

### ISSUE THREAD

**Issue by SidSkiba** [Blair2004/NexoPOS#1854]
The sales tax does not seem to be working. If the product is say 35$ and you have GST at 5% is changes the sale price to 33.33 in POS.

**Comment by Blair2004** [comment]
Hi,
Unfortunately, your issue doesn't seem to have much information that can help us handle this concern. As a reference, issue #501 explains how to create an issue here so we can have much information to help.

Thanks for creating another thread.
