### ISSUE TITLE
[Issue] Barcode image 404 error

### ISSUE THREAD

**Issue by Machaeon** [Blair2004/NexoPOS#1870]
Barcodes are not displayed due to image loading error

**To Reproduce**
1. Go to Inventory - Print labels
2. Select a product
3. Click Apply setting

 NexoPOS vesrion: 5.2.3
![nexo-bar](https://github.com/Blair2004/NexoPOS/assets/10704935/08f677cf-1eb5-402f-bd81-11122713f2ff)

**Comment by Blair2004** [comment]
Hi, sorry for the delay, you might need to create a symlink.
This should guide:

https://my.nexopos.com/en/documentation/troubleshooting/broken-media-images

**Comment by Machaeon** [comment]
Thank you for your reply.
I did a new installation using Laragon. Nexo is installed in the folder D:/laragon/www/nexopos
My auto.nexopos.local.conf looks like this:
```
<VirtualHost *:80> 
    DocumentRoot "D:/laragon/www/nexopos/public"
    ServerName nexopos.local
    ServerAlias *.nexopos.local
    <Directory "D:/laragon/www/nexopos/public">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```
I access the system at the url http://nexopos.local
Executing php artisan storage:link I get this message:
ERROR The [D:\laragon\www\nexopos\public\storage] link already exists.
However, the barcode images are still giving a 404 error.

**Comment by Blair2004** [comment]
<img width="654" alt="Screenshot 2024-06-13 at 10 38 35" src="https://github.com/Blair2004/NexoPOS/assets/5265663/dd531352-d3eb-4015-94d7-d7fc797e6f10">
Seems no longer applicable to v5.2.4 ? Update needed ? Let us know

**Comment by Machaeon** [comment]
The problem persisted for me in version 5.2.5. Downloaded media is displayed normally.

**Comment by Machaeon** [comment]
For me, the problem persists in version 5.2.5. Downloaded media is displayed normally.

**Comment by Blair2004** [comment]
Zip your project (exclude the vendors and node_modules directories) to contact[at]nexopos[dot]com.

If you're a premium user email us by the same mean, will take a look at your setup.

Kind regards

**Comment by Machaeon** [comment]
@Blair2004, thank you for your reply.
Mailed you link to zip.
