### ISSUE TITLE
When I enter Product in product group, select product in it, why is there an error?

### ISSUE THREAD

**Issue by dimaswildanR3** [Blair2004/NexoPOS#1876]
When I enter Product in product group, select product in it, why is there an error?
error 
App\Services\ProductService::searchProduct(): Argument #1 ($search) must be of type string, null given, called in D:\Xampp\htdocs\NexoPOS-5.1.0\app\Http\Controllers\Dashboard\ProductsController.php on line 128

![Screenshot (2049)](https://github.com/Blair2004/NexoPOS/assets/68639276/7e2df3ee-5712-4ef9-adb1-11128940ebd0)

**Comment by Blair2004** [comment]
Hi, thank you for reporting this, we'll investigate on that.

**Comment by Blair2004** [comment]
This should be fixed on v5.2.6
