### ISSUE TITLE
[Issue] npm run build error NexoPos 5.2.3

### ISSUE THREAD

**Issue by dwikychandra21** [Blair2004/NexoPOS#1884]
**Describe the bug**
I got an issue when running command npm run build. but running well when i run php artisan serve

**To Reproduce**
1. run composer install
2. npm install
3. npm run build

**Expected behavior**
The Asset can build for production perfectly

**Screenshots**
<img width="1156" alt="Screenshot 2024-05-02 at 13 05 41" src="https://github.com/Blair2004/NexoPOS/assets/22638332/3ab04e3c-76c0-48ca-8577-d2f58e4b2c67">

**Environment:**
 - NexoPOS vesrion: 5.2.3
 - Node version: 18.17.0

**Comment by dwikychandra21** [comment]
your package.json is not included the Vue library, can you please add it?

**Comment by Blair2004** [comment]
Thank you for reporting... added here https://github.com/Blair2004/NexoPOS/commit/170a7d72aa0dc8c47f979fff880b33425dbdb5bc
Use this branch
