### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [Blair2004/NexoPOS#1891]
**Describe the bug**
When we upload images, and go to the gallery, the images aren't displayed !!!! it only display the alt attribute

**To Reproduce**
1. Go to 'Medias'
2. Click on 'Upload'
3. Go to 'Gallery'

**Expected behavior**
The expected behavior is when we upload images, we should be able to see them in the gallery

**Screenshots**
![image](https://github.com/Blair2004/NexoPOS/assets/79521157/a049bc41-bbff-475e-afda-5f41d0cb58a5)

**Environment:**
 - NexoPOS vesrion: 5.2.4

**Comment by Blair2004** [comment]
Hey,
welcome, try this: 
- https://my.nexopos.com/en/documentation/troubleshooting/images-not-loading
- https://my.nexopos.com/en/documentation/troubleshooting/broken-media-images

**Comment by abdellatif-laghjaj** [comment]
> Hey, welcome, try this:
> 
> * https://my.nexopos.com/en/documentation/troubleshooting/images-not-loading
> * https://my.nexopos.com/en/documentation/troubleshooting/broken-media-images

Thank you @Blair2004

**Comment by Blair2004** [comment]
Feel free to open this thread if that ddidn't worked.
