### ISSUE TITLE
[Issue] Customer Email is still required even if Require Valid Email in settings is set as No

### ISSUE THREAD

**Issue by dovah19** [Blair2004/NexoPOS#1893]
**Issue**
Customer Email is still required even if "Require Valid Email" in customer settings is set as "No"

**To Reproduce**
Create a customer without email

**Screenshots**
![customer settings](https://github.com/Blair2004/NexoPOS/assets/142969757/2b71ad12-9248-4751-b792-d21b2d7dc741)
![email error](https://github.com/Blair2004/NexoPOS/assets/142969757/d3277421-256a-4c57-a47f-91e24d3ffb50)

**Environment:**
 - NexoPOS vesrion: 5.2.4

**Comment by Blair2004** [comment]
Hi,
Thank you for reporting. Normally if the email field is empty, NexoPOS will create a custom email. As customer are also user, they kinda need an email. 

I'll look into this.

**Comment by Blair2004** [comment]
![image](https://github.com/Blair2004/NexoPOS/assets/5265663/1c2e6d14-6519-489c-b1c1-d597f788eecb)

It appears there is a bug on the validation rule for the email field. Normally it should validate if there is any input. 

Still, I'm checking this out.
