### ISSUE TITLE
[Issue] Annual Report Error

### ISSUE THREAD

**Issue by kenzahem** [Blair2004/NexoPOS#1928]
**Describe the bug**
Can't load Annual Reporting and an error appear on the bottom.

**To Reproduce**
1. Go to Reports
2. Annual Reports
3. Pressing LOAD

**Screenshots**
![annual report error](https://github.com/Blair2004/NexoPOS/assets/1901459/edc98178-b17a-4051-9cc0-c912ac17a0ed)

**Environment:**
 - NexoPOS vesrion: 5.2.4
 - Windows 10
 - Laragon

**Comment by Blair2004** [comment]
Hi,
Thank you for reporting. We'll checking this.

**Comment by kenzahem** [comment]
> Hi, Thank you for reporting. We'll checking this.

Thanks Blair.

**Comment by Blair2004** [comment]
This wil be fixed on v5.2.5
