### ISSUE TITLE
sorry to ask. Why is it that when I create a product the product type is group. When selecting any product in that group, why isn't it included?

### ISSUE THREAD

**Issue by dimaswildanR3** [Blair2004/NexoPOS#1934]
https://github.com/Blair2004/NexoPOS/assets/68639276/29300d90-5b8f-4b8c-bb6e-15d3c0261125

**Comment by Blair2004** [comment]
Hi thank you for reporting this.

For further issues, follow these instructions #501 (subsequent invalid formatted issues might be immediately closed).
We'll go ahead with a review based on this video. Consider sharing the following:
- NexoPOS version
- PHP version
- Module used (if any).

Kind regards.
