### ISSUE TITLE
[Issue] provide a title for the issue you're facing here

### ISSUE THREAD

**Issue by bykuzey34** [Blair2004/NexoPOS#1944]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
The issue is unclear.
