### ISSUE TITLE
When i add product i just find errors am using v5 the latest version

### ISSUE THREAD

**Issue by Crooks39822** [Blair2004/NexoPOS#1960]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Invalid error format. Please read #501
