### ISSUE TITLE
[Issue] Error thrown when trying to access edit product

### ISSUE THREAD

**Issue by fahmiegerton** [Blair2004/NexoPOS#1973]
**Describe the bug**
Error when I try to edit the product. I traced back, and found this from ProductCrud.php file

```
if ( $field->isNotEmpty() ) {
    $option = collect( $field[0][ 'options' ] )->filter( fn( $option ) => $option[ 'value' ] === $field[0][ 'value' ] );
    $optionLabel = $option->first()[ 'label' ]; // this one return null and throw an error since it access an array on null
}
```

I was able to access the edit page by adding `$optionLabel = $option->first()[ 'label' ] ?? null`, but the categories and units is missing

**To Reproduce**
1. Go to Inventory Menu > Products
2. Select option > "Edit Product" from one of the products
3. Error thrown

**Expected behavior**
Can access the edit product page

**Screenshots**
![image](https://github.com/Blair2004/NexoPOS/assets/5303871/478a1bbd-f11c-48c6-a66e-1b7ce6ffff3e)

**Environment:**
 - NexoPOS vesrion: 5.2.5
 - Premium Extensions: None

**Comment by Blair2004** [comment]
This error:

![image](https://github.com/Blair2004/NexoPOS/assets/5265663/18e353d7-2298-4edb-bf06-19cb23060352)

Occurs when by some means you delete a unit that was assigned to a unit quantity. NexoPOS forbids deleting a unit that is used by another resource.

![image](https://github.com/Blair2004/NexoPOS/assets/5265663/8a0bbb74-4685-4443-a3d6-ff8458d455e9)

So if you manipulated the database, NexoPOS cannot handle that as you might not have proceeded in a normal way. 
We can't implement this on the app as we've already prevented the deletion of used units.

**Comment by fahmiegerton** [comment]
The weird thing is no, I don't delete it anything from the database nor do I touch the database and it happened everytime I create new product item, and I didn't delete unit from database or from the unit itself

**Comment by fahmiegerton** [comment]
When I debug this `$field[0][ 'options' ]` and this `$field[0][ 'value']`, it does have value, but when using `filter` from the collection, it somehow return empty

**Comment by fahmiegerton** [comment]
Here's the record when I create new product item, as you can see, after I save the item, it redirected to edit page which then thrown an error

[Screencast from 10-07-24 10:25:08.webm](https://github.com/Blair2004/NexoPOS/assets/5303871/928de0de-7978-4c52-9925-b6db186ebb74)

**Comment by Blair2004** [comment]
Send the database to contact@nexopos.com
we'll try to reproduce.

**Comment by fahmiegerton** [comment]
> Send the database to [contact@nexopos.com](mailto:contact@nexopos.com) we'll try to reproduce.

I just did, hope you can find what's wrong with it, or I may misconfigure it, thanks for the help!
