### ISSUE TITLE
[Issue] missing script "prod" on local install

### ISSUE THREAD

**Issue by iamTakuu** [Blair2004/NexoPOS#1985]
**The bug**
When I reach the build stage and run 'npm run prod' I just get an error and cant start the application, here's the log:

```
1 info using npm@10.7.0
2 info using node@v18.20.4
3 silly config:load:file:/home/imp3tuz/.nvm/versions/node/v18.20.4/lib/node_modules/npm/npmrc
4 silly config:load:file:/home/imp3tuz/Desktop/nexopos/.npmrc
5 silly config:load:file:/home/imp3tuz/.npmrc
6 silly config:load:file:/home/imp3tuz/.nvm/versions/node/v18.20.4/etc/npmrc
7 verbose title npm run prod
8 verbose argv "run" "prod"
...
13 verbose stack Error: Missing script: "prod"
13 verbose stack
13 verbose stack To see a list of scripts, run:
13 verbose stack   npm run
13 verbose stack     at RunScript.run (/home/imp3tuz/.nvm/versions/node/v18.20.4/lib/node_modules/npm/lib/commands/run-script.js:79:13)
13 verbose stack     at async module.exports (/home/imp3tuz/.nvm/versions/node/v18.20.4/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 verbose cwd /home/imp3tuz/Desktop/nexopos
15 verbose Linux 6.5.0-41-generic
16 verbose node v18.20.4
17 verbose npm  v10.7.0
18 error Missing script: "prod"
18 error
18 error To see a list of scripts, run:
18 error   npm run
19 verbose exit 1
20 verbose code 1
```

**To Reproduce**
1. Download latest release 
2. run composer install
3. run npm install (even though docs say its not necessary past v4..)
4. run npm run prod

**Screenshots**

Weirdly, running npm run dev, somewhat starts the server?
![image](https://github.com/user-attachments/assets/d37df0de-f5eb-44d4-9c5c-2b2ce75dddee)

![image](https://github.com/user-attachments/assets/dbf83c79-ed8e-40f9-acf7-a6c650b32585)

![image](https://github.com/user-attachments/assets/52d7fdf8-539c-4144-b574-0c8608f9472e)

**Environment:**
 - NexoPOS vesrion: 5.2.5
 - Linux Mint (Ubuntu 22)

**Comment by nexopos** [comment]
Hi,
the right command should actually be "npm run build".

**Comment by iamTakuu** [comment]
Yeah I tried running that and it builds but doesn't work. I'll try again when on my pc and let you know though 👌

**Comment by Blair2004** [comment]
Closed for lack of activity. Feel free to comment if you have any update.
