### ISSUE TITLE
EMERGENCY LIVE DEMO HAVE PROBLEM

### ISSUE THREAD

**Issue by hasanablak** [Blair2004/NexoPOS#1988]
LIVE DEMO HAVE PROBLEM
<img width="1440" alt="Screenshot 2024-07-16 at 23 49 53" src="https://github.com/user-attachments/assets/655e833e-2177-41ce-9269-ea7304746ee3">
<img width="1440" alt="Screenshot 2024-07-16 at 23 50 25" src="https://github.com/user-attachments/assets/d009fa43-244d-4576-ad0d-2cc2485b459c">

**Comment by Blair2004** [comment]
Hi,
Thank you for reporting.
We’ll proceed to a fix

Kind regards.
