### ISSUE TITLE
Error when saving edited product

### ISSUE THREAD

**Issue by simbake** [Blair2004/NexoPOS#2048]
**Describe the bug**
I get the error below when saving an edited product. I am using the master branch.
```App\Jobs\ComputeCategoryProductsJob::__construct(): Argument #1 ($productCategory) must be of type App\Models\ProductCategory, null given, called in C:\xampp\laravel\NexoPOS\vendor\laravel\framework\src\Illuminate\Foundation\Bus\Dispatchable.php on line 19```

**To Reproduce**
View a product and edit it. Try to save after editing it and the error occurs

**Expected behavior**
Should be able to edit and save a product

**Screenshots**

**Environment:**
 - NexoPOS vesrion: 5.2.6

**Comment by Blair2004** [comment]
Hi,
When you edit the product, it appears the category no longer exists. This shouldn't be the case as validation should requires you to provide a category. So, you should check if the category assigned exists. Can you tell if you did some changes to the code?

**Comment by simbake** [comment]
The category does exist and it shows in the category select component. But when I try to save it gives that error. I have not made changes to the code. I have downgraded to v5.1.0 and it works just fine. I did not have enough time troubleshoot. Maybe you can try to investigate. Thanks.

**Comment by Blair2004** [comment]
updating a product on master works so far.
We're unable to reproduce this. When you'll have more details for reproducing, we'll be able to work on that.

![image](https://github.com/user-attachments/assets/2363ed57-edde-4b76-9540-542f04a9ebb5)
