### ISSUE TITLE
Error Connect database

### ISSUE THREAD

**Issue by herybrts** [Blair2004/NexoPOS#2051]
![error nexopos](https://github.com/user-attachments/assets/05a2fba7-3ffd-47a0-b873-771fcf1a28bd)

if i installl and setupup database, always error connect.How to resolve this trouble?

**Comment by herybrts** [comment]
iam install using cpanel hosting

**Comment by Blair2004** [comment]
Hi, sorry for the issue you're facing. It appears that you might not have correctly deployed NexoPOS. 

You see, when you deploy NexoPOS, the access to the domain (with no extra argument on the url like /public/do-setup) is the correct of installing.

You should therefore make sure you domain Document Root is pointing to the folder "public" located at the root of NexoPOS.

Hope this helps.

**Comment by Blair2004** [comment]
If this did'nt helped, feel free to reopen.
