### ISSUE TITLE
[Issue] problem to add product to product group

### ISSUE THREAD

**Issue by caribouman** [Blair2004/NexoPOS#2074]
**Describe the bug**
impossible to add procduct to prodcut group

**To Reproduce**
create 2 products materialized with unit called 'piece' with value of 1

after trying to create a product group and when try to add product , i can select te unit of the product i select but after click on unit  have this message in console

TypeError: Cannot read properties of undefined (reading 'value')
    at manage-products-cca5b591.js:1:2558
    at Proxy.filter (<anonymous>)
    at Proxy.addResult (manage-products-cca5b591.js:1:2517)

![image](https://github.com/user-attachments/assets/dce13f7b-191b-4796-871a-dce58f83819c)

**Screenshots**
![image_8](https://github.com/user-attachments/assets/2ffd1532-be9b-42fa-807a-f90d92ebe91b)

**Environment:**
 - NexoPOS vesrion: 5.2.6
 - Premium Extensions: gastro, bulk importer

**Comment by Blair2004** [comment]
Hi,
thank you for reporting,
we're checking this.
