### ISSUE TITLE
Issue: "Unknown Occurrence" and Errors When Triggering Recurring Transactions in NexoPOS

### ISSUE THREAD

**Issue by mohammed-fatah** [Blair2004/NexoPOS#2076]
Description:

I am encountering an issue with recurring transactions in NexoPOS where the occurrence type is displayed as "Unknown Occurrence" in the UI, despite setting a valid recurrence type. Additionally, I am unable to manually trigger recurring transactions, while scheduled transactions can be triggered without any issues.
Steps to Reproduce:

Create a recurring transaction (e.g., rent payment) and set the occurrence type to a valid option (e.g., "Monthly").
Save the transaction.
In the UI, the Occurrence column displays "Unknown Occurrence" for the recurring transaction.
Attempt to manually trigger the recurring transaction by clicking Options → Trigger. This results in an error: "This transaction type can't be triggered."
Create a scheduled transaction and attempt to trigger it. The transaction triggers successfully but still displays "Unknown Occurrence."

What I’ve Tried:

I updated the occurrence field in the ns_nexopos_transactions table to month_starts and set occurrence_value to 1 (representing the first day of the month).
I also set the scheduled_date field to a future date (2024-10-01), but the issue persists, with the UI still displaying "Unknown Occurrence."
I confirmed that the recurring field is set to 1 to indicate a recurring transaction.

Relevant Database Info:

Here’s what my database looks like for one of the transactions:

    sql
    
    SELECT id, name, recurring, occurrence, occurrence_value, scheduled_date 
    FROM ns_nexopos_transactions WHERE id = 5;
    
    +----+-------------------------------+-----------+--------------+------------------+---------------------+
    | id | name                          | recurring | occurrence   | occurrence_value | scheduled_date      |
    +----+-------------------------------+-----------+--------------+------------------+---------------------+
    |  5 | rent payment building monthly |         1 | month_starts | 1                | 2024-10-01 00:00:00 |
    +----+-------------------------------+-----------+--------------+------------------+---------------------+

    The occurrence is set to month_starts, and occurrence_value is set to 1.
    The scheduled_date is set to 2024-10-01, but the UI continues to show "Unknown Occurrence."

Environment:

    NexoPOS Version: 4.x
    PHP Version: 5.2.1
    Database: MySQL 8.0
    Setup: Running NexoPOS in Docker containers on a Raspberry Pi 5

Steps Taken in the Docker Environment:

The application is running inside Docker containers (Nginx, MySQL, PHP-FPM) on a Raspberry Pi 5.
The queue worker is running using QUEUE_CONNECTION=database, and jobs are processed correctly.

Expected Behavior:

The occurrence type (e.g., "Monthly" or "Scheduled") should be displayed correctly in the UI instead of "Unknown Occurrence."
Manually triggering recurring transactions should work without errors, similar to scheduled transactions.

Screenshots:

Scheduled Transaction (Triggered Successfully):
![Screenshot 2024-09-20 084227](https://github.com/user-attachments/assets/10ac492e-6457-4d66-b180-d2302dbbf640)
Scheduled Transaction

Recurring Transaction (Trigger Error):
![image](https://github.com/user-attachments/assets/8dfcec91-b803-49ff-b465-0510b4367656)
Recurring Transaction Error

Questions for the Developer:

- Is there a known issue with how recurrence types are stored or displayed for recurring transactions?
- Could the occurrence_value or scheduled_date fields be causing this behavior, or is there another field or logic I need to configure?
- Why are scheduled transactions able to trigger successfully, but recurring transactions show the error: "This transaction type can't be triggered"?
- Is there additional configuration or debugging I should do to resolve this issue?

Thank you for your help, and thank you for all the hard work you put into NexoPOS!

**Comment by Blair2004** [comment]
Hi 
I'll try answering:

1 - No there is no known issue regarding that.
2 - unknown occurrence might be a missing support for that type, but recurring transaction are supported so it might be a bug.
3 - Recurring transaction can't be triggered, only one-time transaction (direct) can be triggered. Recurring transaction are triggered with condition are met by the system.
4—Scheduled transactions trigger once in the future; the only difference with direct transactions is the moment they execute.

Use direct transaction instead of recurring if you would like to manually trigger it.

**Comment by mohammed-fatah** [comment]
> Hi I'll try answering:
> 
> 1 - No there is no known issue regarding that. 2 - unknown occurrence might be a missing support for that type, but recurring transaction are supported so it might be a bug. 3 - Recurring transaction can't be triggered, only one-time transaction (direct) can be triggered. Recurring transaction are triggered with condition are met by the system. 4—Scheduled transactions trigger once in the future; the only difference with direct transactions is the moment they execute.
> 
> Use direct transaction instead of recurring if you would like to manually trigger it.

Dear @Blair2004,

Thank you so much for your quick response and the clarification!

That makes sense regarding the manual triggering. Based on your explanation, I would like to test recurring transactions, but I’m unsure how to do this properly. Could you provide guidance on how recurring transactions are triggered by the system?

Also, do I need to ensure that Laravel workers (e.g., queue:work) are running for recurring transactions to trigger automatically, or is there a different process I should follow?

Thanks again for your help!
