### ISSUE TITLE
[click on dashboard link then given error "Unauthenticated."

### ISSUE THREAD

**Issue by kapasia24** [Blair2004/NexoPOS#2103]
**Describe the bug**
When I click on any link of Dashboard of NexoPOS in my server then not open link page and given error "Unauthenticated."
**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Any link'
3. See error "Unauthenticated"

**Expected behavior**
I want to open link page with expected form without error

**Screenshots**
![image](https://github.com/user-attachments/assets/601de97a-e11a-4e33-b9aa-74e8bd14470b)

**Environment:**
 - NexoPOS vesrion: [e.g. 3]

**Comment by Blair2004** [comment]
Hi can you include a link to your dashboard ? You might exclude the domain.

**Comment by kapasia24** [comment]
https://www.dreamjapanedu.com/dashboard/pos
User: Deshadmin & Passowrd: codeastro.com

**Comment by nzian** [comment]
> https://www.dreamjapanedu.com/dashboard/pos User: Deshadmin & Passowrd: codeastro.com

Please check SANCTUM_STATEFUL_DOMAINS in .env files. your web routes all okay. Only api url is the problem. and that happned when stateful domain not same domains as you access from.

Thank you.

**Comment by Blair2004** [comment]
> https://www.dreamjapanedu.com/dashboard/pos
> 
> User: ****** & Passowrd: ********

Do not share credentials on a public page.

**Comment by Blair2004** [comment]
if you access your website with "www.dreamjapanedu.com" and have your domain defined "dreamjapanedu.com" on your .env you'll have this issue. the same way, if you access your website as dreamjapanedu.com while on the .env it's defined www.dreamjapanedu.com you'll still have that issue. make sure to use one domain (either with the subdomain www or without).
