### ISSUE TITLE
Expenses menu not showing

### ISSUE THREAD

**Issue by Gringo2** [Blair2004/NexoPOS#2118]
**Describe the bug**
i have successfully installed nexopos in ln my local machine but expenses mudule is not show in the list of menus

version nexopos 5.2.7

**Comment by Blair2004** [comment]
Hi, please consider using NexoPOS 5.3.x we have a different way of dealing with expenses there:

- https://my.nexopos.com/en/documentation/components/expenses
- https://my.nexopos.com/en/documentation/components/accounting-incomes-expenses

Feel free to reopen if the issue persists.
