### ISSUE TITLE
[Issue] TypeError: Cannot read properties of null (reading 'taxes')

### ISSUE THREAD

**Issue by whendy** [Blair2004/NexoPOS#2131]
On the POS page, when selecting a product without a tax group, an error will appear as shown below. The selected product does not appear yet, but when opening or closing the developer tools, the selected product will display.

**Screenshots**
![Screenshot at 2024-11-12 14-28-01](https://github.com/user-attachments/assets/04e4d633-1e36-49f4-8396-66285ce6f5ec)

**Environment:**
 - NexoPOS vesrion: v5.3.0

**Comment by Blair2004** [comment]
Hi, 
Sorry for the late reply, we might need to see the location of the error on the file pos-init.ts. You might additionally share your database at contact@nexopos.com.

Best.

**Comment by whendy** [comment]
Hello @Blair2004 just set value **NULL** at field **tax_group_id** on table **nexopos_products**

![tax_broup_id-null-products](https://github.com/user-attachments/assets/9edc82c7-43f2-4491-aec7-7f2e07096fbe)

**Comment by whendy** [comment]
I think this issue can be closed. 
use version v.5.3.2.
Thank @Blair2004
