### ISSUE TITLE
[Issue] Cashier Double Register History

### ISSUE THREAD

**Issue by whendy** [Blair2004/NexoPOS#2132]
There are frequent duplicate entries in the cashier's registration history.

**Screenshots**
![Screenshot at 2024-11-12 15-38-36](https://github.com/user-attachments/assets/cce52a84-25ba-4060-9a54-9423c2b0dce7)

**Environment:**
 - NexoPOS vesrion: v5.2.7

**Comment by Blair2004** [comment]
Hi, 
consider using a more recent NexoPOS version.
Let us know how it goes.
