### ISSUE TITLE
[Issue] Can't click the payment button on the POS screen

### ISSUE THREAD

**Issue by whendy** [Blair2004/NexoPOS#2133]
**Describe the bug**
When clicking the pay button, there is no response. The error encountered is shown in the image below.

**Screenshots**
![Screenshot at 2024-11-12 17-39-05](https://github.com/user-attachments/assets/553f6abb-2b78-48a3-bac6-f67939235ad0)

https://github.com/user-attachments/assets/0bea6311-c983-4f71-8779-5a78cd0530e0

**Environment:**
 - NexoPOS version: v5.3.0

**Comment by Blair2004** [comment]
Hi,
sorry for the delays. We need more insight on the error. Consider opening the error file as mentioned on the log. Otherwise, share your database to contact@nexopos.com

**Comment by ayoub-hs** [comment]
i confirm pay button is not working after updating from 5.2.7 to 5.3.0

**Comment by Blair2004** [comment]
![image](https://github.com/user-attachments/assets/b5158075-6451-4dd2-8ea7-56801efedb20)

Hi either send the file or provide a screenshot of that file

**Comment by whendy** [comment]
At line 25049/25088

![25088-nexopos](https://github.com/user-attachments/assets/9461644d-b463-4ae5-9709-094b62ac5cd8)


At line 60427

![60427-nexopos](https://github.com/user-attachments/assets/16dab8bb-0677-4ff8-a79f-cd8d2f28cf70)

**Comment by Blair2004** [comment]
Hi, please reach out (contact@nexopos.com) for a live access to your computer during working hours (9am - 6pm GMT+1)
It's quite weird that this.order.products is not defined. By any chance have you changed the code ?

**Comment by whendy** [comment]
I haven't changed or modified any code. Just switched branch tags from 5.2.7 to 5.3.0

**Comment by ayoub-hs** [comment]
me too when upgraded to 5.3.0

**Comment by ayoub-hs** [comment]
even 5.3.1 didn't work for me

**Comment by whendy** [comment]
I think this issue can be closed. 
use version v.5.3.2.
Thank @Blair2004
