### ISSUE TITLE
[Issue] i cant sign in when switch langauge to arabic 

### ISSUE THREAD

**Issue by TaGoat** [Blair2004/NexoPOS#2191]
**Describe the bug**
user name or password is not correct

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Thank you for reporting, we're checking this.

**Comment by Blair2004** [comment]
Unfortunately, after switching to Arabic on NexoPOS 5.3.2, we can log in.
We need further details about the instance.

reopen when available.
